#ifndef __COCBFDEF_H
#define __COCBFDEF_H

/* ----- Automaticaly generated by P4 stamps - Do not edit! ----- */
#ifndef ACCELL
static char rcs_id_cocbfdef_h_46C47A01[] = "#(@) 46C47A01 $Id: //training/cortex/base/common/common_4.1/src/include/cocbfdef.h#1 $";
static char rcs_datetime_cocbfdef_h_46C47A01[] = "#(@) 46C47A01 $DateTime: 2008/08/18 14:01:31 $";
static char rcs_change_cocbfdef_h_46C47A01[] = "#(@) 46C47A01 $Change: 60878 $";
static char rcs_author_cocbfdef_h_46C47A01[] = "#(@) 46C47A01 $Author: sdods $";
#endif
/* ------------------------ End of P4 stamps -------------------- */
/*---------------------------Includes-----------------------------------*/
/*---------------------------Externs------------------------------------*/
/*---------------------------Macros-------------------------------------*/
					/* values for C_MSGCLS		*/
#define MCL_AUTH 	'1'		/* authorisation		*/
#define MCL_FIN		'2'		/* financial			*/
#define MCL_FILE	'3'		/* file update			*/
#define MCL_REVCB	'4'		/* reversal / chargeback	*/
#define MCL_RECON	'5'		/* reconciliation		*/
#define MCL_ADMIN	'6'		/* administrative		*/
#define MCL_FEE		'7'		/* fee collection		*/
#define MCL_NETMGT	'8'		/* network management		*/

					/* values for C_MSGFN		*/
#define MFN_REQ		'0'		/* request			*/
#define MFN_REQRSP	'1'		/* request response		*/
#define MFN_ADV		'2'		/* advice			*/
#define MFN_ADVRSP	'3'		/* advice response		*/
#define MFN_NOTIF	'4'		/* notification			*/

					/* values for C_TXNSRC		*/
#define MOR_ACQ		'0'		/* acquirer			*/
#define MOR_ACQRPT	'1'		/* acquirer repeat		*/
#define MOR_ISS		'2'		/* card issuer			*/
#define MOR_ISSRPT	'3'		/* card issuer repeat		*/
#define MOR_GEN		'4'		/* general			*/
#define MOR_GENRPT	'5'		/* general repeat		*/

					/* values for C_FNCODE		*/
					/* 1xx used in AUTH msgs	*/
#define MFC_AUTH_ORG_AMT_ACC	100	/* orig auth, amount accurate	*/
#define MFC_AUTH_ORG_AMT_EST	101	/* org auth, amount estimated	*/
#define MFC_AUTH_RPL_AMT_ACC	102	/* rpl auth, amount accurate	*/
#define MFC_AUTH_RPL_AMT_EST	103	/* rpl auth, amt estimated	*/
#define MFC_AUTH_RESUB_AMT_ACC	104	/* resubmission, amount accurate*/
#define MFC_AUTH_RESUB_AMT_EST	105	/* resubmission, amount estim	*/
#define MFC_AUTH_SUPP_AMT_ACC	106	/* supplement, amount accurate	*/
#define MFC_AUTH_SUPP_AMT_EST	107	/* supplement, amount estim	*/
#define MFC_AUTH_INQUIRY	108	/* inquiry			*/
					/* 109-119 reserved ISO		*/
				/* NMR5637 M.Davey 1/6/2001 deleted 120 */
					/* 121-159 reserved ISO		*/
					/* 160-179 reserved national	*/
					/* 180-199 reserved PRIVATE	*/
#define MFC_AUTH_ACCVER_ONLY	180	/* acc/addr verification only	*/
#define MFC_AUTH_TELVER_ONLY	181	/* telecode verification only	*/
#define MFC_AUTH_CUSTVER_ONLY	182	/* customer verification only	*/

					/* 2xx used in FIN msgs		*/
#define MFC_FIN_ORG		200	/* original financial req/adv	*/
#define MFC_FIN_PRV_AUTH_SAME	201	/* previously auth'd, amt same	*/
#define MFC_FIN_PRV_AUTH_DIFF	202	/* prev auth'd, amt differs	*/
#define MFC_FIN_PRV_DENIED	203	/* resubmission of prev denied	*/
#define MFC_FIN_PRV_REV		204	/* resubmission of prev reversed*/
#define MFC_FIN_REPRES1		205	/* first representation		*/
#define MFC_FIN_REPRES2		206	/* second representation	*/
#define MFC_FIN_REPRES3		207	/* third or subsequent repres	*/
					/* 208-259 reserved ISO		*/
					/* 260-279 reserved national	*/
					/* 280-299 reserved PRIVATE	*/
#define MFC_FIN_REPRES_PART1	282	/* partial repres (ECCF)	*/

					/* 3xx used in File Update	*/
#define MFC_FILE_UNASS		300	/* unassigned			*/
#define MFC_FILE_ADDREC		301	/* add record			*/
#define MFC_FILE_CHGREC		302	/* change record		*/
#define MFC_FILE_DELREC		303	/* delete record		*/
#define MFC_FILE_RPLREC		304	/* replace record		*/
#define MFC_FILE_INQUIRY	305	/* inquiry			*/
#define MFC_FILE_RPLFILE	306	/* replace file			*/
#define MFC_FILE_ADDFILE	307	/* add file			*/
#define MFC_FILE_DELFILE	308	/* delete file			*/
#define MFC_FILE_CRDADM		309	/* card admin			*/
					/* 310-359 reserved ISO		*/
					/* 360-379 reserved national	*/
					/* 380-399 reserved PRIVATE	*/

					/* 40x used in Reversal		*/
#define MFC_FULL_REV		400	/* full reversal, txn not cmplt	*/
#define MFC_PART_REV		401	/* part reversal, txn not cmplt	*/
					/* 402-419 reserved ISO		*/
					/* 420-439 reserved national	*/
					/* 440-449 reserved PRIVATE	*/
#define MFC_FULL_REPRES_REV	445	/* full representment rev	*/
#define MFC_PART_REPRES_REV	446	/* partial representment rev	*/

					/* 45x used in Chargeback	*/
#define MFC_CHBK_FULL1		450	/* full chargeback, first	*/
#define MFC_CHBK_FULL2		451	/* full chargeback, second	*/
#define MFC_CHBK_FULL3		452	/* full chargeback, 3rd & subs	*/
#define MFC_CHBK_PART1		453	/* part chargeback, first	*/
#define MFC_CHBK_PART2		454	/* part chargeback, second	*/
#define MFC_CHBK_PART3		455	/* part chargeback, 3rd & subs	*/
					/* 456-469 reserved ISO		*/
					/* 470-489 reserved national	*/
					/* 490-499 reserved PRIVATE	*/
#define MFC_CHBK_REV1		490	/* chargeback reversal, 1	*/
#define MFC_CHBK_REV2		491	/* chargeback reversal, 2	*/
#define MFC_CHBK_REV3		492	/* chargeback reversal, 3	*/
#define MFC_CHBK_PTREV1		493	/* part chargeback reversal, 1	*/
#define MFC_CHBK_PTREV2		494	/* part chargeback reversal, 2	*/
#define MFC_CHBK_PTREV3		495	/* part chargeback reversal, 3	*/

					/* 5xx used in Recon Totals	*/
#define	MFC_RECON_FINAL_REC	500	/* final reconciliation		*/
#define	MFC_RECON_CPNT_REC	501	/* checkpoint reconciliation	*/
#define	MFC_RECON_FINAL_RECCUR	502	/* final rec, specified curr	*/
#define	MFC_RECON_CPNT_RECCUR	503	/* checkpoint rec, spec curr	*/
#define	MFC_RECON_TOTALS_REQ	504	/* reconciliation tots request	*/
					/* 505-539 reserved ISO		*/
					/* 540-569 reserved national	*/
					/* 570-599 reserved PRIVATE	*/
					/* VISA, SMS			*/
#define	MFC_RECON_ACQ_GIV	570	/* 272 Acquirer GIV totals	*/
#define	MFC_RECON_ACQ_GIV_NA	571	/* 273 Acquirer GIV totals N/A	*/
#define	MFC_RECON_ISS_GIV	572	/* 274 Issuer GIV totals	*/
#define	MFC_RECON_ISS_GIV_NA	573	/* 275 Issuer GIV totals N/A	*/
#define	MFC_RECON_ACQB_CUT	574	/* 261 Acq. batch cutoff totals	*/
#define	MFC_RECON_ACQSIB_CUT	575	/* 262 Acq. standin cutoff tots	*/
#define	MFC_RECON_ISSB_CUT	576	/* 263 Iss. batch cutoff totals	*/
#define	MFC_RECON_ISSSIB_CUT	577	/* 264 Iss. standin cutoff tots	*/
#define	MFC_RECON_ACQS_CUT	578	/* 265 Acq. settl cutoff totals	*/
#define	MFC_RECON_ACQSIS_CUT	579	/* 266 Acq. standin cutoff tots	*/
#define	MFC_RECON_ISSS_CUT	580	/* 267 Iss. settl cutoff totals	*/
#define	MFC_RECON_ISSSIS_CUT	581	/* 268 Iss. standin cutoff tots	*/
#define	MFC_RECON_ACQB_CUT_NA	582	/* 281 Acq. batch cutoff tot NA	*/
#define	MFC_RECON_ACQSIB_CUT_NA	583	/* 282 Acq. standin cut tots NA	*/
#define	MFC_RECON_ISSB_CUT_NA	584	/* 283 Iss. batch cutoff tot NA	*/
#define	MFC_RECON_ISSSIB_CUT_NA	585	/* 284 Iss. standin cut tots NA	*/
#define	MFC_RECON_ACQS_CUT_NA	586	/* 285 Acq. settl cutoff tot NA	*/
#define	MFC_RECON_ACQSIS_CUT_NA	587	/* 286 Acq. standin cut tots NA	*/
#define	MFC_RECON_ISSS_CUT_NA	588	/* 287 Iss. settl cutoff tot NA	*/
#define	MFC_RECON_ISSSIS_CUT_NA	589	/* 288 Iss. standin cut tots NA	*/

					/* 6xx used in Admin		*/
					/* 600-649 retrieval requests	*/
#define	MFC_CREQ_ORG_RQ		600	/* original rcpt, retrieval rq	*/
#define	MFC_CREQ_ORG_RQRP	601	/* original rcpt, repeat rq	*/
#define	MFC_CREQ_ORG_FULF	602	/* original rcpt, fulfilment	*/
#define	MFC_CREQ_CPY_RQ		603	/* copy rcpt, retrieval rq	*/
#define	MFC_CREQ_CPY_RQRP	604	/* copy rcpt, repeat rq		*/
#define	MFC_CREQ_CPY_FULF	605	/* copy rcpt, fulfilment	*/
#define	MFC_CREQ_VEHREN		606	/* vehicle rental		*/
#define	MFC_CREQ_HOTEL		607	/* hotel charge detail		*/
#define	MFC_CREQ_POSPHO		608	/* POS photograph		*/
#define	MFC_CREQ_PRFDEL		609	/* proof of delivery		*/
#define	MFC_CREQ_IMPRINT	610	/* imprint			*/
					/* WLi 06/07/2000		*/
#define	MFC_ICC_PVT		611	/* PVT 600/610			*/
#define	MFC_ICC_INFOADV		612	/* ICC infomation advice 620/630*/
					/* 613-629 reserved ISO		*/
					/* 630-639 reserved national	*/
					/* 640-649 reserved PRIVATE	*/
#define	MFC_FRAUD_ADV		640	/* VISA-type fraud advice	*/
#define	MFC_TEXT_MSG		641	/* 883 VISA free text message	*/
#define	MFC_FXFR_TOT		642	/* 290 VISA funds xfer totals	*/
#define	MFC_CREQ_STATUS		643	/* 884 VISA copy request status	*/

					/* Europay ECCSS private */
#define MFC_EURO_REQUEST_CANCEL	644	/* Euro copy request cancel(S44)*/
#define MFC_EURO_REQRESP_CANCEL	645	/* Request Response Cancel (S44) */

					/* 650-659 also used in Admin	*/
#define	MFC_ADMIN_EPARSE_MSG	650	/* Unable to parse message	*/
					/* 651-669 reserved ISO		*/
					/* 670-689 reserved national	*/
					/* 690-699 reserved PRIVATE	*/
					/* NMR 5637 M.Davey 1/6/2001 EMV*/
#define MFC_EMV_ADVICE		690	/* EMV advice (in 1620 msg)     */

					/* 7xx used in Fee collection	*/
#define MFC_FEE_COLLECT		700	/* fee collection		*/
#define MFC_FEE_CANCEL		701	/* fee collection cnx full/part	*/
					/* 702-759 reserved ISO		*/
					/* 760-779 reserved national	*/
#define MFC_FC_RTN_RV		760	/* reversal of 780 (IPM) */
#define MFC_FC_RESUB_RV		761	/* reversal of 781 (IPM) */
#define MFC_FC_ARB_RTN_RV	762	/* reversal of 782 (IPM) */
					/* 780-799 reserved PRIVATE	*/
#define MFC_FEE_COLL_RTN	780	/* fee collection return (IPM) */
#define MFC_FEE_COLL_RESUB	781	/* fee collection resubmission (IPM) */
#define MFC_FEE_COLL_ARB_RTN	782	/* fee collection arbitration return (IPM) */

					/* 8xx used in Net Management	*/
#define	MFC_NETMGT_SIGN_ON	801	/* Sign on to network		*/
#define	MFC_NETMGT_SIGN_OFF	802	/* Sign off network		*/
#define	MFC_NETMGT_SYS_NA	803	/* System unavaiable		*/
					/* 807-810 reserved ISO		*/
#define	MFC_NETMGT_SEC_KEY_CHG	811	/* security / key change	*/
#define	MFC_NETMGT_SEC_ALERT	812	/* security / alert		*/
#define	MFC_NETMGT_SEC_PSW_CHG	813	/* security / password change	*/
#define	MFC_NETMGT_SEC_DVC_AUT	814	/* security / device authent	*/
					/* 815-820 reserved ISO		*/
#define	MFC_NETMGT_ACC_CUTOVER	821	/* sysacct / cutover		*/
#define	MFC_NETMGT_ACC_CHKPOINT	822	/* sysacct / checkpoint		*/
					/* 823-830 reserved ISO		*/
#define	MFC_NETMGT_ECHO		831	/* system audit / echo test	*/
					/* 832-850 reserved ISO		*/
					/* 860-879 reserved national	*/
					/* 880-899 reserved PRIVATE	*/
					/* VISA, BASE I			*/
#define	MFC_NETMGT_ENTER_SI	880	/* 062 - enter SI mode		*/
#define	MFC_NETMGT_EXIT_SI	881	/* 063 - exit SI mode		*/
#define	MFC_NETMGT_NEXT_ADV	882	/* 066 - prompt for next advice	*/
#define	MFC_NETMGT_START_ADV	883	/* 068 - start trans. advices	*/
#define	MFC_NETMGT_STOP_ADV	884	/* 069 - stop trans. advices	*/
#define	MFC_NETMGT_EOF_ADV	MFC_NETMGT_STOP_ADV
					/* Internal - VISA/VIP IF	*/
/*				885	UNUSED				*/
/*				886	UNUSED				*/
#define	MFC_NETMGT_RQ_KEY_CHG	887	/* 101 Key change request	*/
#define	MFC_NETMGT_RQ_NEW_AWK	888	/* 160 Request new AWK		*/
#define	MFC_NETMGT_RQ_NEW_IWK	889	/* 161 Request new IWK		*/
#define	MFC_NETMGT_DL_NEW_AWK	890	/* 162 Deliver new AWK		*/
#define	MFC_NETMGT_DL_NEW_IWK	891	/* 163 Deliver new IWK		*/
#define	MFC_NETMGT_RQ_DAY_TOT	892	/* 270 Request current rec tot	*/
#define	MFC_NETMGT_RQ_PRV_TOT	893	/* 280 Request previous rec tot	*/
#define	MFC_NETMGT_REJECT	894	/* Europay reject message	*/

					/* ISO 93 Host Interface	*/
#define	MFC_NETMGT_UPLD		896	/* Start upload (no sign-on)	*/
#define MFC_NETMGT_UPLD_SIGNON	897	/* Start upload after sign-on.	*/

					/* 9xx unassigned	 	*/
					/* 900-939 reserved ISO		*/
					/* 940-969 reserved national	*/
					/* 970-999 reserved PRIVATE	*/

					/* values for C_REASONCODE	*/
					/* 0000-0999 Reserved ISO	*/
/*** NB Nomad have hijacked 0001-0999 for VISA chargeback reason code	*/
					/* 1000-1499 reason for advice	*/
#define MRC_ADV_STIP_ISS	1000	/* Stand-in req. by issuer	*/
#define MRC_ADV_ISS_SOFF	1001	/* issuer signed off		*/
#define MRC_ADV_ISS_TOUT	1002	/* issuer timed out on request	*/
#define MRC_ADV_ISS_UNAV	1003	/* issuer unavailable		*/
#define MRC_ADV_TRM_PROC	1004	/* terminal processed		*/
#define MRC_ADV_ICC_PROC	1005	/* ICC processed		*/
#define MRC_ADV_BLW_FLR		1006	/* below floor limit		*/
#define MRC_ADV_STIP_ACQ	1007	/* Stand-in req by acq		*/
					/* 1008-1150 reserved ISO	*/
					/* 1151-1375 reserved national	*/
					/* 1376-1499 reserved PRIVATE	*/
#define MRC_ADV_REV_CMP		1377	/* Prev revd trn did complete	*/
#define MRC_CLR_AUTH_TRN	1378	/* Clearing authorised trn	*/
#define MRC_CLR_UNAU_TRN	1379	/* Clearing un-authorised trn	*/
#define MRC_CLR_AREV_CMP	1380	/* Prev revd adj did complete	*/
#define MRC_ADV_UNSOLCASH	1381	/* Unsolicited cashin deposit	*/
					/* NMR013667 WLi 05/7/2005	*/
					/* for UK Maestro adjustments	*/
#define	MRC_ADV_ORG_AMT		1382	/* Original amount incorrect	*/
#define	MRC_ADV_DUP_TXN		1383	/* Duplicate transmission	*/
#define	MRC_ADV_REC_ERR		1384	/* Reconcile error		*/
#define	MRC_ADV_SUS_MAL		1385	/* System malfunction		*/
					/* 1500-1999 reason for request	*/
#define MRC_REQ_ICC_CDF		1500	/* ICC, common data file prob	*/
#define MRC_REQ_ICC_ADF		1501	/* ICC, applic data file prob	*/
#define MRC_REQ_ICC_RAND	1502	/* ICC, random selection	*/
#define MRC_REQ_TRM_RAND	1503	/* term, random selection	*/
#define MRC_REQ_TRM_NICC	1504	/* term cannot process ICC	*/
#define MRC_REQ_FRC_ICC		1505	/* on-line forced by ICC	*/
#define MRC_REQ_FRC_ACC		1506	/* on-line forced by acceptor	*/
#define MRC_REQ_FRC_CAD		1507	/* on-line forced CAD updated	*/
#define MRC_REQ_FRC_TRM		1508	/* on-line forced by term	*/
#define MRC_REQ_FRC_ISS		1509	/* on-line forced by issuer	*/
#define MRC_REQ_OVR_FLR		1510	/* over floor limit		*/
#define MRC_REQ_MRCH_SUS	1511	/* merchant suspicious		*/
					/* 1512-1650 reserved ISO	*/
					/* 1651-1775 reserved national	*/
					/* 1776-1999 reserved PRIVATE	*/
#define MRC_REQ_SUS_FRAUD	1776	/* suspected fraud NOMAD	*/
#define MRC_REQ_SECURITY	1777	/* security reasons NOMAD	*/
#define MRC_REQ_ICC_BITMAP3	1778	/* ICC, 3rd bitmap data problem	*/
					/* 2xxx used in Represent msgs	*/
#define MRC_REP_INV_CHBK	2000	/* general - invalid chbk	*/
#define MRC_REP_INV_ARN		2001	/* invalid acquirer ref		*/
#define MRC_REP_NO_DOC		2002	/* no required supporting doc	*/
#define MRC_REP_CORR_DATE	2003	/* correct date provided	*/
#define MRC_REP_CORR_DESC	2004	/* correct mrch dscr provided	*/
#define MRC_REP_CORR_LOC	2005	/* correct mrch locn provided	*/
#define MRC_REP_INV_DATE	2006	/* invalid date on chbk		*/
#define MRC_REP_BELOW_FL	2007	/* below merchant floor limit	*/
#define MRC_REP_ISS_AUTH	2008	/* issuer authorised txn	*/
#define MRC_REP_AMT_OK		2009	/* no error in addition		*/
#define MRC_REP_NO_ALTER	2010	/* no proof of altered amount	*/
#define MRC_REP_CREDITED	2011	/* credit already issued	*/
#define MRC_REP_ORG_VALID	2012	/* original txn was valid	*/
					/* 3xxx used in File Maint	*/
#define MRC_FIL_LOST		3000	/* Lost Card			*/
#define MRC_FIL_STOLEN		3001	/* Stolen Card			*/
#define MRC_FIL_UNDELIVERED	3002	/* Undelivered Card		*/
#define MRC_FIL_COUNTERFEIT	3003	/* Counterfeit Card		*/
					/* AMEX specific codes		*/
#define MRC_FIL_COLLECTION	3700	/* Collection			*/
#define MRC_FIL_BNK_NEG		3701	/* Bank Negative		*/
#define MRC_FIL_INSPECTOR	3702	/* Inspector			*/
#define MRC_FIL_VIP		3703	/* VIP Status Indicator		*/
					/* 40xx used in Reversal	*/
#define MRC_REV_CUST_CNX	4000	/* customer cancellation	*/
#define MRC_REV_NO_ACT		4001	/* no action taken		*/
#define MRC_REV_SUS_MAL		4002	/* suspected malfunction	*/
#define MRC_REV_FMT_ERR		4003	/* format error, no action taken*/
#define MRC_REV_PART		4004	/* completed partially		*/
#define MRC_REV_ORG_AMT		4005	/* original amount incorrect	*/
#define MRC_REV_TOO_LATE	4006	/* response received too late	*/
#define MRC_REV_NOT_CMP		4007	/* device unable to complete	*/
#define MRC_REV_DEP_BAL		4008	/* deposit out of balance	*/
#define MRC_REV_NO_CHK		4009	/* no check in enevlope		*/
#define MRC_REV_PAY_BAL		4010	/* payment out of balance	*/
#define MRC_REV_DEP_BAL_APP	4011	/* dep out of bal/content applid*/
#define MRC_REV_PAY_BAL_APP	4012	/* paymt out/bal, content applid*/
#define MRC_REV_MSG_NOT_DEL	4013	/* message not delivered to POS	*/
#define MRC_REV_MAL_CRD_CAP	4014	/* malfunction, card captured	*/
#define MRC_REV_MAL_CRD_RET	4015	/* malfunction, card returned	*/
#define MRC_REV_T3_NOT_UPD	4016	/* malfunction, T3 not updated	*/
#define MRC_REV_NO_CSH		4017	/* malfunction, no cash dispense*/
#define MRC_REV_TOUT_CSH	4018	/* cash take timeout, no cash	*/
#define MRC_REV_TOUT_CRD	4019	/* card take timeout, no cash	*/
#define MRC_REV_INV_RSP		4020	/* invalid response, no action	*/
#define MRC_TOUT_WAIT_RSP	4021	/* timeout waiting for response */
					/* 4022-4199 reserved ISO	*/
					/* 4200-4350 reserved national	*/
					/* 4351-4499 reserved PRIVATE	*/
#define MRC_ADJ_CUST_CNX	4351	/* ADJ: partial return		*/
#define MRC_ADJ_PART		4352	/* ADJ: partial disp/wrong amt	*/
#define MRC_REV_PART_RETURN	4353	/* ADJ: partial return		*/
#define MRC_REV_ACQ_ERROR	4354	/* ADJ: acquirer error		*/
#define MRC_REV_NOT_CONF	4355	/* no confirm from POS		*/
#define MRC_REV_POSS_DUP	4356	/* VISA - possible duplicate	*/
#define MRC_REV_DUP_TXN		4357	/* VISA - duplicate txn		*/
#define MRC_REV_DUP_NREP	4358	/* VISA - BII dup txn not repre	*/
#define MRC_REV_FNCL_2_FOLLOW	4359	/* ISO93Host - Auth reversal.  	*/
					/* 45x used in Chgback		*/
#define MRC_CHB_INV_MRCH	4500	/* invalid merchant		*/
#define MRC_CHB_INV_TXN		4501	/* invalid transaction		*/
#define MRC_CHB_CUS_DIS		4502	/* customer dispute		*/
#define MRC_CHB_EXPIRED		4503	/* expired card			*/
#define MRC_CHB_NOT_TRM		4504	/* txn not permitted to term	*/
#define MRC_CHB_SEC_VIO		4505	/* security violation		*/
#define MRC_CHB_SYS_MAL		4506	/* system malfunction		*/
#define MRC_CHB_DSP_AMT		4507	/* disputed amount		*/
#define MRC_CHB_OVRAUTH		4508	/* txn exceeds authd amt	*/
#define MRC_CHB_AUTHEXP		4509	/* auth time limit expired	*/
#define MRC_CHB_CRASDR		4510	/* credit submitted as debit	*/
#define MRC_CHB_DRASCR		4511	/* debit submitted as credit	*/
#define MRC_CHB_DUPTXN		4512	/* duplicate txn		*/
#define MRC_CHB_NOTCR		4513	/* credit not rcd		*/
#define MRC_CHB_FRAUD		4514	/* fraudulent txn		*/
#define MRC_CHB_NOTFIN		4515	/* txn not finalised		*/
#define MRC_CHB_NOFULF		4516	/* request not fulfilled	*/
#define MRC_CHB_CPILLG		4517	/* copy illegible		*/
#define MRC_CHB_NOTREC		4518	/* cardholder not recognise	*/
#define MRC_CHB_NOSTIP		4519	/* stand-in proc not allowed	*/
#define MRC_CHB_INSTIP		4520	/* stand-in criteria not ok	*/
#define MRC_CHB_OVR_LIM		4521	/* txn over floor limit		*/
#define MRC_CHB_DECLINE		4522	/* txn was declined		*/
#define MRC_CHB_ACCMTCH		4523	/* account number mismatch	*/
#define MRC_CHB_ERRADD		4524	/* error in addition		*/
#define MRC_CHB_ALTAMT		4525	/* altered amount		*/
#define MRC_CHB_NOSIG		4526	/* no signature			*/
#define MRC_CHB_NOIMP		4527	/* no imprint			*/
#define MRC_CHB_CNXPRE		4528	/* cancelled preauth		*/
#define MRC_CHB_DLQREC		4529	/* delinquent reconciliation	*/
#define MRC_CHB_CURCNV		4530	/* currency conversion		*/
#define MRC_CHB_CLAIM		4531	/* claim on defective goods	*/
#define MRC_CHB_DEFECT		4532	/* defective merchandise	*/
#define MRC_CHB_PREEFF		4533	/* fraud pre effective date	*/
#define MRC_CHB_MULTSL		4534	/* imprint of multiple slips	*/
#define MRC_CHB_EXFILE		4535	/* on card exception file	*/
#define MRC_CHB_LATE		4536	/* late presentment		*/
#define MRC_CHB_NOSHOW		4537	/* no show disputed		*/
#define MRC_CHB_ADLODG		4538	/* advance loding deposit	*/
#define MRC_CHB_DTDISP		4539	/* cardholder disputes date 	*/
#define MRC_CHB_NOTEFF		4540	/* card not yet effective 	*/
#define MRC_CHB_ILLEG		4541	/* illegible data	 	*/
#define MRC_CHB_NOTRCD		4542	/* txn not received	 	*/
#define MRC_CHB_DUPPRO		4543	/* duplicate processing	 	*/
#define MRC_CHB_CNXREC		4544	/* cancelled recurring txn 	*/
#define MRC_CHB_CNVNAL		4545	/* currency conversion not all.	*/
#define MRC_CHB_MAILUN		4546	/* mail/telephone unauthorised	*/
#define MRC_CHB_CWB		4547	/* card on warning bulletin	*/
#define MRC_CHB_DSPBFL		4548	/* dispute - below floor	*/
#define MRC_CHB_INCACC		4549	/* incorrect account number	*/
#define MRC_CHB_DSPCTL		4550	/* disputed card-activated tel 	*/
#define MRC_CHB_ORGCUR		4551	/* original txn curr not prov 	*/
#define MRC_CHB_MAILEX		4552	/* mail/tel txn on expired card	*/
#define MRC_CHB_TXNNAD		4553	/* txn not as described		*/
#define MRC_CHB_NOMCHD		4554	/* merchandise not received	*/
#define MRC_CHB_NOSVC		4555	/* services not rendered	*/
#define MRC_CHB_MCHDDS		4556	/* merchandise not as described	*/
					/* 4557-4649 reserved ISO	*/
					/* 4650-4749 reserved national	*/
					/* 4780-4999 reserved PRIVATE	*/
#define MRC_CHB_PLUS_CHDCR	4780 	/* Cardholder disp (credit)	  */
#define MRC_CHB_PLUS_CHDDR	4781 	/* Cardholder disp (debit)	  */
#define MRC_CHB_PLUS_RVPCRCHB	4782 	/* Reversal prev credit chgbk	  */
#define MRC_CHB_PLUS_RVPDRCHB	4783 	/* Reversal prev debit chgbk	  */
#define MRC_CHB_PLUS_CHDSPRVA	4784 	/* Cardholder dispute prv adj	  */
#define MRC_CHB_PLUS_INVADJRC	4785 	/* Invalid adjustment recvd	  */
#define MRC_CHB_PLUS_ACCLOSED	4786 	/* Invalid adjustment recvd	  */

/* Private use so using these for FDS	*/
#define MRC_FDS_FRAUD		4790	/* FDS rejected / fraud		*/
#define MRC_FDS_FRAUD_PICKUP	4791	/* FDS rejected & crd retrived	*/

					/* 5xxx Reason for a reconc.	*/
					/* 5000-5299 reserved ISO	*/
/*** NB Nomad have hijacked 5000-5299 for VISA fee/funds reason code	*/
					/* 5300-5599 reserved national	*/
					/* 5600-5999 reserved PRIVATE	*/

					/* 6000-6499 Reason for Retriev	*/
#define MRC_RRQ_CHDISP		6001	/* cardholder dispute		*/
#define MRC_RRQ_CHDMND		6002	/* cardholder demand		*/
#define MRC_RRQ_CBKDOC		6003	/* chargeback documentation	*/
#define MRC_RRQ_LEGINV		6004	/* legal/fraud investigation	*/
#define MRC_RRQ_LEGREQ		6005	/* legal request		*/
#define MRC_RRQ_FRAUDA		6006	/* fraud analysis		*/
#define MRC_RRQ_WRITNG		6007	/* handwriting analysis		*/
#define MRC_RRQ_CHRSIG		6008	/* cardholder req paper sign	*/
#define MRC_RRQ_REQTE		6009	/* request for T&E doc		*/
#define MRC_RRQ_ORGLST		6010	/* original lost in transit	*/
#define MRC_RRQ_WRTDMN		6011	/* written demand for orig	*/
#define MRC_RRQ_LEGORG		6012	/* legal process requires org	*/
#define MRC_RRQ_PRVILL		6013	/* previous copy illegible	*/
#define MRC_RRQ_NOTREC		6014	/* cardholder does not recog	*/
#define MRC_RRQ_NOTAGR		6015	/* cardholder disputs amt	*/
#define MRC_RRQ_PERSON		6016	/* cardholder requires personal	*/
#define MRC_RRQ_LEGSIG		6017	/* legal dispute signature	*/
#define MRC_RRQ_LEGAMT		6018	/* legal dispute amount		*/
#define MRC_RRQ_LEGIMP		6019	/* legal dispute imprint	*/
					/* 6020-6199 reserved ISO	*/
					/* 6200-6299 reserved national	*/
					/* 6300-6499 reserved PRIVATE	*/

					/* 6500-6999 Reason for Admin	*/
					/* 6500-6599 reserved ISO	*/
					/* 6600-6799 reserved national	*/
					/* 6800-6999 reserved PRIVATE	*/

					/* 7xxx Reason for fee coll	*/
					/* 7000-7299 reserved ISO	*/
					/* 7300-7599 reserved national	*/
					/* 7600-7999 reserved PRIVATE	*/

					/* 8xxx Reason for net mgt	*/
					/* 8000-8299 reserved ISO	*/
					/* 8300-8599 reserved national	*/
					/* 8600-8999 reserved PRIVATE	*/

					/* 9xxx Reason for ???		*/
					/* 9000-9299 reserved ISO	*/
					/* 9300-9599 reserved national	*/
					/* 9600-9999 reserved PRIVATE	*/

					/* values for C_POSCHIC		*/
#define MCHIC_UNK		'0'	/* unknown			*/
#define MCHIC_MAN		'1'	/* manual, no terminal		*/
#define MCHIC_MAG		'2'	/* mag stripe read		*/
#define MCHIC_BAR		'3'	/* bar code			*/
#define MCHIC_OCR		'4'	/* OCR				*/
#define MCHIC_ICC		'5'	/* integrated chip card		*/
#define MCHIC_KEY		'6'	/* key entered			*/
#define	MCHIC_CLICC_UNK		'7'	/* contactless ICC (and unknown)*/
					/* (Not for our terminals,use A/B)*/
#define	MCHIC_CLMAG_UNK		'8'	/* contactless msr (and unknown)*/
					/* (Not for our terminals,use C/D)*/
#define MCHIC_MAGCVV            '9'     /* PRIVATE - full track read    */
#define MCHIC_CLICC_ICC		'A'	/* Contactless ICC + contact ICC */
#define MCHIC_CLICC_NOICC	'B'	/* Contactless ICC (no contact ICC)*/
/* Below 2 are very unlikely, but may appear */
#define MCHIC_CLMAG_ICC		'C'	/* Contactless MSR + contact ICC */
#define MCHIC_CLMAG_NOICC	'D'	/* Contactless MSR (no contact ICC) */
/* NOTE: POSCHIC changes - you must check load_f61poschic() 
 * and set_f61poschic() in epif/epclt code */

					/* values for C_POSCHAC		*/
#define MCHAC_NOEL		'0'	/* no electronic authentication	*/
#define MCHAC_PIN		'1'	/* PIN				*/
#define MCHAC_ESIG		'2'	/* electronic signature analysis*/
#define MCHAC_BIOM		'3'	/* biometrics			*/
#define MCHAC_BIOG		'4'	/* biographic			*/
#define MCHAC_INOP		'5'	/* electronic auth inoperative	*/
#define MCHAC_COMB		'6'	/* combination of 1-4 above	*/
#define MCHAC_NOPIN		'8'	/* PRIVATE PIN pad down		*/
#define MCHAC_MSUS		'9'	/* Merchant suspicious		*/

					/* values for C_POSCRC		*/
#define MCRC_NONE		'0'	/* none				*/
#define MCRC_CAPT		'1'	/* capture capability		*/

					/* values for C_POSOE		*/
#define MOE_NOTRM		'0'	/* no terminal used		*/
#define MOE_ONP_ATT		'1'	/* on premises, attended	*/
#define MOE_ONP_UNA		'2'	/* on premises, unattended	*/
#define MOE_OFP_ATT		'3'	/* off premises, attended	*/
#define MOE_OFP_UNA		'4'	/* off premises, unattended	*/
#define MOE_ONCH_UNA		'5'	/* on CH premises, unattended	*/

					/* values for C_POSCHP		*/
#define MCHP_PRES		'0'	/* cardholder present		*/
#define MCHP_UNSP		'1'	/* not present, unspecified	*/
#define MCHP_MAIL		'2'	/* not present, mail order	*/
#define MCHP_TELE		'3'	/* not present, telephone	*/
#define MCHP_STAND		'4'	/* not present, standing auth	*/
#define	MCHP_EORD		'5'	/* electronic order, WLi 25/08/00 */
#define MCHP_PRESSTAND		'6'	/* crdhlr present, standing auth*/
#define MCHP_INST		'9'	/* PRIVATE n/pres, installation	*/

					/* values for C_POSCP		*/
#define MCP_NOTP		'0'	/* card not present		*/
#define MCP_PRES		'1'	/* card present			*/

					/* values for C_POSCDIM		*/
#define MCDIM_UNK		'0'	/* unspecified			*/
#define MCDIM_MAN		'1'	/* manual, no terminal		*/
#define MCDIM_MAG		'2'	/* mag stripe read		*/
#define MCDIM_BAR		'3'	/* bar code			*/
#define MCDIM_OCR		'4'	/* OCR				*/
#define MCDIM_ICC		'5'	/* integrated chip card		*/
#define MCDIM_KEY		'6'	/* manually keyed		*/
#define	MCDIM_CLICC		'7'	/* contactless ICC, N10998 WLi	*/
#define	MCDIM_ICC9		'8'	/* ICC, but the data may not be
					reliable, WLi 06/07/2000	*/
#define MCDIM_MAGCVV		'9'	/* PRIVATE - full track read	*/
					/* For E-commerce */
/* S,T,A,B new values as 3D secure replaces SET */
#define MCDIM_3DSECMRCH		'S'	/* Merchant supports 3D secure  */
#define MCDIM_3DSEC		'T'	/* Full 3D secure transaction   */
#define MCDIM_ESEC              'V'     /* E-Commerce with channel enc  */
#define MCDIM_ENOSEC            'U'     /* E-Commerce no security	*/
					/* For SET level extend		*/
#define	MCDIM_3DSECMRCHC	'A'	/* As S and chip cryptogram used */
#define	MCDIM_3DSECC		'B'	/* As T and chip cryptogram used */
#define	MCDIM_ESECC		'C'	/* As V and chip cryptogram used */
#define	MCDIM_CLMAG		'E'	/* contactless mag stripe, N10998 WLi*/
#define	MCDIM_AMXVOICE		'F'	/* AMEX voice auth network to issuer only */

/* Obsolete POSCDIM values now SET is withdrawn */
#define MCDIM_SETNOCH           'S'     /* old: SET no Crdhldr cert     */
#define MCDIM_SETCH             'T'     /* old: SET with Crdhldr Cert   */
#define	MCDIM_SETNOCHC		'A'	/* old: As S and chip EMV AC used */
#define	MCDIM_SETCHC		'B'	/* old: As T and chip EMV AC used */
#define	MCDIM_ESECM		'D'	/* As V but merchant is capable of
					   supporting SET, WLi 14/09/2000 */

					/* values for C_POSCHAM		*/
#define MCHAM_NOTA		'0'	/* not authenticated		*/
#define MCHAM_PIN		'1'	/* PIN				*/
#define MCHAM_ESIG		'2'	/* electronic signature analysis*/
#define MCHAM_BIOM		'3'	/* biometrics			*/
#define MCHAM_BIOG		'4'	/* biographic			*/
#define MCHAM_MSIG		'5'	/* manual signature verification*/
#define MCHAM_MOTH		'6'	/* manual other (eg licence)	*/
#define MCHAM_EC		'9'	/* E-Commerce txn		*/

					/* values for C_POSCHA		*/
#define MCHA_NOTA		'0'	/* not authenticated		*/
#define MCHA_ICC		'1'	/* integrated chip card		*/
#define MCHA_CAD		'2'	/* ISO 10202 = terminal		*/
#define MCHA_AAG		'3'	/* authorising agent		*/
#define MCHA_MCH		'4'	/* merchant			*/
#define MCHA_OTH		'5'	/* other			*/

/* NB BELOW POSCHAD AND POSSD ARE NOW OBSOLETE !!!			*/
					/* values for C_POSCHAD		*/
#define MCHAD_NONE		'0'	/* none				*/
#define MCHAD_PIN		'1'	/* PIN				*/
#define MCHAD_ESIG		'2'	/* electronic signature		*/
#define MCHAD_BIOM		'3'	/* biometrics			*/
#define MCHAD_BIOG		'4'	/* biographic			*/
#define MCHAD_OTH		'5'	/* other			*/

					/* values for C_POSSD		*/
#define MSD_NONE		'0'	/* no concern			*/
#define MSD_SUSP		'1'	/* merchant suspicious		*/
#define MSD_IVER		'2'	/* identification verified	*/
#define MSD_NICC		'3'	/* term can't read chip card	*/
#define MSD_ICC_NAC		'4'	/* ICC not accessible		*/
#define MSD_ICC_CDF		'5'	/* ICC CDF not accessible	*/
#define MSD_ICC_ADF		'6'	/* ICC ADF not accessible	*/
#define MSD_SUS_FRAUD		'8'	/* PRIVATE suspect fraud	*/
#define MSD_SECURITY		'9'	/* PRIVATE security		*/
/* NB ABOVE POSCHAD AND POSSD ARE NOW OBSOLETE !!!			*/

 					/* values for C_POSCDOC		*/
 					/* Card data output capabilty	*/
#define MCDOC_UNK		'0'	/* unknown			*/
#define MCDOC_NONE		'1'	/* none				*/
#define MCDOC_MAG		'2'	/* mag stripe write		*/
#define MCDOC_ICC		'3'	/* integrated chip card		*/

					/* values for C_POSTOC		*/
 					/* Terminal output capabilty	*/
#define MTOC_UNK		'0'	/* unknown			*/
#define MTOC_NONE		'1'	/* none				*/
#define MTOC_PRINT		'2'	/* printing			*/
#define MTOC_DSPLY		'3'	/* display			*/
#define MTOC_PRNDS		'4'	/* print & display		*/

					/* values for C_POSPCC		*/
#define MPCC_NONE		'0'	/* no PIN capture capability	*/
#define MPCC_UNK		'1'	/* PIN capture capabilty unknown*/
#define MPCC_4			'4'	/* 4 digits			*/
#define MPCC_5			'5'	/* 5 digits			*/
#define MPCC_6			'6'	/* 6 digits			*/
#define MPCC_7			'7'	/* 7 digits			*/
#define MPCC_8			'8'	/* 8 digits			*/
#define MPCC_9			'9'	/* 9 digits			*/
#define MPCC_10			'A'	/* 10 digits			*/
#define MPCC_11			'B'	/* 11 digits			*/
#define MPCC_12			'C'	/* 12 digits			*/

				/* WLi 06/07/2000 */
/* Chip Condition Code - Reports status of current transaction
 * and the previous transaction on the same terminal. (Visa defined) */
				/* Values for C_POSCCC */
#define	MCCC_NO26	'0'	/* Not an ICC->MSR fallback txn */
#define	MCCC_SUCC	'1'	/* This txn is ICC->MSR fallback,
				 * previous txn not ICC->MSR fallback */
#define	MCCC_FAIL	'2'	/* This and previous txn are both ICC->MSR
				 * fallback (on same terminal) */

				/* Values for C_POSCCPS */
#define	MCCPS_NO	'0'	/* Nonchip-based transaction */
#define	MCCPS_YES	'1'	/* Chip-based transaction */
				/* NMR013841 WLi 11/7/2004
				 * value 2 is only used by VISA interface
				 * as switch */
#define	MCCPS_F134EXP	'2'	/* Chip txn and acquirer uses F134 expanded */
#define	MCCPS_DNGRD	'3'	/* Downgraded chip txn, N15163 WLi 03/02/2006 */

				/* Values for C_POSCARI */
#define	MCARI_UNK	'0'	/* Unknown */
#define	MCARI_NO	'1'	/* Acquirer indicates CA may not be reliable */
#define	MCARI_ACQ	'2'	/* VisaNet indicates acquirer inactive for CA */
#define	MCARI_ISS	'3'	/* VisaNet indicates issuer inactive for CA */

				/* Values for C_POSCHIM, WLi 17/08/2000 */
#define	MCHIM_UNK	'0'	/* Not specified */
#define	MCHIM_ISG	'1'	/* Signature */
#define	MCHIM_PIN	'2'	/* PIN	*/
#define	MCHIM_TER	'3'	/* Unattended terminal, no PIN pad */
#define	MCHIM_MAT	'4'	/* Mail/Telephone */

					/* values for C_ACTIONCODE	*/
#define MAC_AUTH_APP		'0'	/* authorisation approved	*/
#define MAC_AUTH_DENIED		'1'	/* authorisation denied		*/
#define MAC_AUTH_DENIED_PU	'2'	/* authorisation denied, pickup	*/
#define MAC_FILE		'3'	/* file actions			*/
#define MAC_REVCB		'4'	/* reversal/chargeback actions	*/
#define MAC_RECON		'5'	/* reconciliation		*/
#define MAC_ADMIN		'6'	/* administrative		*/
#define MAC_FEE			'7'	/* fee collection		*/
#define MAC_NETMGT		'8'	/* network management		*/
#define MAC_ERROR		'9'	/* error response action	*/

					/* values for C_RSPCODE		*/
					/* 0xx - auth approvals		*/
#define MRS_AAPP_APP		"00"	/* approved			*/
#define MRS_AAPP_HWI		"01"	/* honour with ID		*/
#define MRS_AAPP_PART		"02"	/* approval for partial amt	*/
#define MRS_AAPP_VIP		"03"	/* approved VIP			*/
#define MRS_AAPP_UT3		"04"	/* approved, update T3		*/
#define MRS_AAPP_ATCI		"05"	/* approved, account type 	*
					 * specified by card issuer	*/
#define MRS_AAPP_PARTATCI	"06"	/* approved for partial amount, *
					 * account type specified by	*
					 * card issuer			*/
#define MRS_AAPP_UICC		"07"	/* approved, update ICC		*/

					/* 008-059 ISO use		*/
					/* 060-079 National use		*/
					/* 080-099 Private use		*/
					/* Following are Nomad private	*/
					/* NMR006186 WLi 05/09/2001	*/
#define	MRS_AAPP_OFFLIN		"80"	/* ICC offline approved		*/
#define	MRS_AAPP_CNTONL		"81"	/* ICC unable to go online, approved*/
#define MRS_AAPP_AAR		"82"	/* ICC approved after card- 	*
					 * initiated referral (AAR)	*/

					/* 1xx - denials, no pickup	*/
#define MRS_ADEN_DENY		"00"	/* do not honour		*/
#define MRS_ADEN_CRDEXP		"01"	/* card expired			*/
#define MRS_ADEN_SFRAUD		"02"	/* suspected fraud		*/
#define MRS_ADEN_CNTACQ		"03"	/* acceptor contact acquirer	*/
#define MRS_ADEN_CRDRST		"04"	/* restricted card		*/
#define MRS_ADEN_ACQSEC		"05"	/* acceptor contact security dpt*/
#define MRS_ADEN_PINTRY		"06"	/* PIN tries exceeded		*/
#define MRS_ADEN_CNTISS		"07"	/* acceptor contact issuer	*/
#define MRS_ADEN_ISSCND		"08"	/* refer to issuer special cond	*/
#define MRS_ADEN_INVMCH		"09"	/* invalid merchant		*/
#define MRS_ADEN_INVAMT		"10"	/* invalid amount		*/
#define MRS_ADEN_INVCRD		"11"	/* invalid card num		*/
#define MRS_ADEN_PINREQ		"12"	/* PIN required			*/
#define MRS_ADEN_BADFEE		"13"	/* unacceptable fee		*/
#define MRS_ADEN_NOACTY		"14"	/* no account of specified type	*/
#define MRS_ADEN_BADFUN		"15"	/* function not supported	*/
#define MRS_ADEN_INSUFF		"16"	/* insufficient funds		*/
#define MRS_ADEN_BADPIN		"17"	/* bad PIN			*/
#define MRS_ADEN_CRDREC		"18"	/* no card record		*/
#define MRS_ADEN_CHTRAN		"19"	/* trans not allowed to cardhldr*/
#define MRS_ADEN_TRTRAN		"20"	/* trans not allowed to terminal*/
#define MRS_ADEN_EXCLIM		"21"	/* exceeds amount limit		*/
#define MRS_ADEN_SCVIOL		"22"	/* security violation		*/
#define MRS_ADEN_EXCFRQ		"23"	/* exceeds frequency limit	*/
#define MRS_ADEN_LWVIOL		"24"	/* violation of law		*/
#define MRS_ADEN_CRDNEF		"25"	/* card not effective		*/
#define MRS_ADEN_INVPBL		"26"	/* invalid PIN block		*/
#define MRS_ADEN_PINLEN		"27"	/* PIN length error		*/
#define MRS_ADEN_PINSYN		"28"	/* PIN key sync error		*/
#define MRS_ADEN_SCNTFT		"29"	/* suspect counterfeit		*/
					/* 130-159 ISO reserved		*/
					/* 160-179 National use reserved*/
					/* Following are Nomad private	*/
#define MRS_ADEN_CHISS		"70"	/* Cardholder contact issuer	*/
#define MRS_ADEN_PINNOTCHG	"71"	/* PIN not changed		*/
#define MRS_ADEN_NO_1GEN_AC	"72"	/* ICC 1st GEN AC failed (no AC)*/
#define MRS_ADEN_INVCUR		"77"	/* invalid currency code-AMEX	*/
#define MRS_ADEN_AAR		"78"	/* ICC decline, after card-	*
					 * initiated referral (AAR)	*/
#define MRS_ADEN_UNSAFEPIN	"79"	/* PIN Change Declined, 	*
					 * (new pin unsafe)		*/
					/* 180-199 Private use 		*/
#define MRS_ADEN_AMTNDV		"80"	/* amount not divisible		*/
#define MRS_ADEN_AMT2BG		"81"	/* amount too big for ATM	*/
#define MRS_ADEN_NOCASH		"82"	/* ATM out of cash		*/
#define MRS_ADEN_NOCQAC		"83"	/* No chequing account		*/
#define MRS_ADEN_DIFPIN		"84"	/* New PINs entered differ	*/
#define MRS_ADEN_CVVERR		"85"	/* CVV validation error		*/
#define MRS_ADEN_TIMLIM		"86"	/* pre-auth time limit exceeded	*/
#define MRS_ADEN_CRDDEL		"87"	/* Card has been destroyed	*/
#define MRS_ADEN_NOFUN		"88"	/* Restricted card. No funds	*/
#define MRS_ADEN_NOFRX		"89"	/* Forex not available  	*/
#define MRS_ADEN_LIMIT		"90"	/* Txn count limit exceeded	*/
#define MRS_ADEN_OVERLOAD	"91"	/* System overload retry poss	*/
#define MRS_ADEN_NOSTMTDATA	"92"	/* Statement data not avail   	*/
#define MRS_ADEN_PINTRYE	"93"	/* Pin tries exceeded		*/
#define MRS_ADEN_NOBALDATA	"94"	/* no balance data available 	*/
					/* WLi 06/07/2000 */
#define	MRS_ADEN_OFFLIN		"95"	/* ICC offline declined		*/
#define	MRS_ADEN_CNTONL		"96"	/* ICC unable to go online, declined*/
#define	MRS_ADEN_CRDATF		"97"	/* ICC card authentication failed*/
/* 1/98 ICC decline after AAR moved to 1/78 (Mark) */
					/* JP 11/02/2002  Mobile Topup	*/
#define MRS_ADEN_RECEIPT	"98"	/* No receipt avail on ATM	*/
#define	MRS_ADEN_NOTUC		"99"	/* No TUC number available	*/
					/* JP 11/02/2002  Mobile Topup	*/


					/* 2xx - denials, pickup	*/
#define MRS_FDEN_DENY		"00"	/* do not honour		*/
#define MRS_FDEN_NSUPPR		"01"	/* not supported by receiver	*/
#define MRS_FDEN_SFRAUD		"02"	/* suspected fraud		*/
#define MRS_FDEN_CNTACQ		"03"	/* acceptor contact acquirer	*/
#define MRS_FDEN_CRDRST		"04"	/* restricted card		*/
#define MRS_FDEN_ACQSEC		"05"	/* acceptor contact security dpt*/
#define MRS_FDEN_PINTRY		"06"	/* PIN tries exceeded		*/
#define MRS_FDEN_SPCOND		"07"	/* special conditions		*/
#define MRS_FDEN_CRDLST		"08"	/* lost card			*/
#define MRS_FDEN_CRDSTL		"09"	/* stolen card			*/
#define MRS_FDEN_SCNTFT		"10"	/* suspect counterfeit		*/
					/* 211-259 ISO use		*/
					/* 260-279 National use		*/
					/* 280-299 Private use		*/
					/* NOMAD private		*/
#define MRS_FDEN_CVVERR		"85"	/* CVV validation error		*/

					/* 3xx - file action result	*/
#define MRS_FILE_OK		"00"	/* accepted			*/
#define MRS_FILE_NOTSUP		"01"	/* not supportted by receiver	*/
#define MRS_FILE_NOREC		"02"	/* unable to locate record	*/
#define MRS_FILE_DUPRPL		"03"	/* duplicate, old rec replaced	*/
#define MRS_FILE_EDIT		"04"	/* field edit error		*/
#define MRS_FILE_LOCKED		"05"	/* file locked			*/
#define MRS_FILE_FAILED		"06"	/* not successful		*/
#define MRS_FILE_FORMAT		"07"	/* format error			*/
#define MRS_FILE_DUPREJ		"08"	/* duplicate, new record rej	*/
#define MRS_FILE_BADFL		"09"	/* unknown file			*/
					/* Following are Nomad private	*/
#define MRS_FILE_INVIID		"80"	/* invalid IID (BIN) VISA 15	*/
#define MRS_FILE_NOTISS		"81"	/* not card issuer VISA 63	*/
#define MRS_FILE_MALSYS		"82"	/* system malfunction VISA 96	*/
#define MRS_FILE_HIPRIOR	"83"	/* file update not accepted, higer*/
					/* priority item on file, AMEX 380*/

					/* 4xx - rev/chbk result	*/
#define MRS_REV_OK		"00"	/* accepted			*/

					/* 5xx - reconciliation rsp	*/
#define	MRS_RECON_OK		"00"	/* Accepted, totals balance	*/
#define	MRS_RECON_OUTBAL	"01"	/* Accepted, totals don't bal	*/
#define	MRS_RECON_ANRCTP	"02"	/* amt not recon, tots provided	*/
#define	MRS_RECON_NOTOTS	"03"	/* totals not available		*/
#define	MRS_RECON_NRECTP	"04"	/* not recon, tots provided	*/
#define	MRS_RECON_ERROR		"99"	/* Nomad private - recon error	*/

					/* 6xx - admin msg rsp		*/
#define	MRS_ADMIN_OK		"00"	/* Accepted			*/
#define	MRS_ADMIN_NOTRACE	"01"	/* Unable to trace orig		*/
#define	MRS_ADMIN_INVREF	"02"	/* Invalid reference		*/
#define	MRS_ADMIN_PANREF	"03"	/* PAN/reference incompat	*/
#define	MRS_ADMIN_NOPHOT	"04"	/* No photo available		*/
#define	MRS_ADMIN_ITMSUP	"05"	/* Item supplied		*/
#define	MRS_ADMIN_NOTAVL	"06"	/* Item not available		*/

					/* 7xx - fee rsp		*/
#define	MRS_FEE_OK		"00"	/* Accepted			*/

					/* 8xx - net management rsp	*/
#define	MRS_NETMGT_OK		"00"	/* Accepted			*/
#define	MRS_NETMGT_REJ		"80"	/* Accepted			*/

					/* 900-901 - req/advice acks	*/
#define MRS_RRSP_OK		"00"	/* accepted, no financial liab	*/
#define MRS_RRSP_OKFLAC		"01"	/* accepted, fin liabilty acc	*/

					/* 902-949 - request responses	*/
#define MRS_RRSP_INVTRN		"02"	/* invalid transaction		*/
#define MRS_RRSP_REENTR		"03"	/* re-enter transaction		*/
#define MRS_RRSP_FORMAT		"04"	/* format error			*/
#define MRS_RRSP_ACQNSP		"05"	/* acquirer not supported	*/
#define MRS_RRSP_CUTOVR		"06"	/* cutover in progress		*/
#define MRS_RRSP_ISINOP		"07"	/* issuer/switch inoperatiive	*/
#define MRS_RRSP_NOROUT		"08"	/* destination not found	*/
#define MRS_RRSP_MALSYS		"09"	/* system malfunction		*/
#define MRS_RRSP_ISSOFF		"10"	/* issuer signed off		*/
#define MRS_RRSP_ISSTIM		"11"	/* issuer timed out		*/
#define MRS_RRSP_ISSUNA		"12"	/* issuer unavailable		*/
#define MRS_RRSP_DUPTRN		"13"	/* duplicate transaction	*/
#define MRS_RRSP_NOORIG		"14"	/* unable to trace original txn	*/
#define MRS_RRSP_RECERR		"15"	/* reconciliation/chkpnt error	*/
#define MRS_RRSP_MACERR		"16"	/* MAC incorrect		*/
#define MRS_RRSP_MACSYN		"17"	/* MAC key sync error		*/
#define MRS_RRSP_NOKEYS		"18"	/* no comms keys avail		*/
#define MRS_RRSP_ENCSYN		"19"	/* encryption key sync error	*/
#define MRS_RRSP_SECAGN		"20"	/* security error - try again	*/
#define MRS_RRSP_SECNOA		"21"	/* security error - no action	*/
#define MRS_RRSP_BADSEQ		"22"	/* message out of sequence	*/
#define MRS_RRSP_RQINPR		"23"	/* request in progress		*/
#define MRS_RRSP_BADDATE	"40"	/* Invalid date/time		*/

					/* 950-999 - advice responses 	*/
#define MRS_ARSP_OK		"00"	/* accepted			*/
#define MRS_ARSP_DISAGR		"50"	/* disagreement			*/
#define MRS_ARSP_CRDEXP		"51"	/* card expired			*/
#define MRS_ARSP_SFRAUD		"52"	/* suspected fraud		*/
#define MRS_ARSP_CRDRST		"53"	/* restricted card		*/
#define MRS_ARSP_INVMCH		"54"	/* invalid merchant		*/
#define MRS_ARSP_INVAMT		"55"	/* invalid amount		*/
#define MRS_ARSP_INVCRD		"56"	/* invalid card num		*/
#define MRS_ARSP_BADFEE		"57"	/* unacceptable fee		*/
#define MRS_ARSP_INSUFF		"58"	/* insufficient funds		*/
#define MRS_ARSP_BADPIN		"59"	/* bad PIN			*/
#define MRS_ARSP_CHTRAN		"60"	/* trans not allowed to cardhldr*/
#define MRS_ARSP_TRTRAN		"61"	/* trans not allowed to terminal*/
#define MRS_ARSP_EXCLIM		"62"	/* exceeds amount limit		*/
#define MRS_ARSP_SCVIOL		"63"	/* security violation		*/
#define MRS_ARSP_EXCFRQ		"64"	/* exceeds frequency limit	*/
#define MRS_ARSP_LWVIOL		"65"	/* violation of law		*/
#define MRS_ARSP_RECERR		"66"	/* reconciliation/chkpnt error	*/
#define MRS_ARSP_MACERR		"67"	/* MAC incorrect		*/
#define MRS_ARSP_MACSYN		"68"	/* MAC key sync error		*/
#define MRS_ARSP_NOKEYS		"69"	/* no comms keys avail		*/
#define MRS_ARSP_ENCSYN		"70"	/* encryption key sync error	*/
#define MRS_ARSP_SECAGN		"71"	/* security error - try again	*/
#define MRS_ARSP_SECNOA		"72"	/* security error - no action	*/
#define MRS_ARSP_BADSEQ		"73"	/* message out of sequence	*/

					/* values for C_TXNCODE		*/
					/* 00-19 Debits			*/
#define MTC_MIN_DEBIT		0	/* minimum debit code		*/
#define MTC_GOODS		0	/* Goods & service		*/
#define MTC_CASH		1	/* Cash				*/
#define MTC_ADJ			2	/* debit adjustment		*/
#define MTC_DEBADJ		2	/* synonym for debit adj	*/
#define MTC_CHQGUA		3	/* cheque guarantee		*/
#define MTC_CHQVER		4	/* cheque verification		*/
#define MTC_EURO		5	/* Eurocheque			*/
#define MTC_TC			6	/* travellers cheque		*/
#define MTC_LOC			7	/* letter of credit		*/
#define MTC_GIRO		8	/* Giro (postal banking)	*/
#define MTC_CBACK		9	/* goods & services with cash	*/
#define MTC_NONCSH		10	/* non-cash instrument		*/
#define MTC_QUASICASH		11	/* quasicasa (TCs etc)		*/
#define MTC_GOODS_TIP		17	/* goods/sale with tip PRIVATE	*/
#define MTC_FEE_COLLECT		19	/* fee collection		*/
#define MTC_MAX_DEBIT		19	/* maximum debit code		*/

					/* 20-29 Credits		*/
#define MTC_MIN_CREDIT		20	/* minimum credit code		*/
#define MTC_RETURN		20	/* returns			*/
#define MTC_REFUND		20	/* synonym for return		*/
#define MTC_DEPOS		21	/* deposit			*/
#define MTC_ADJUST		22	/* credit adjustment		*/
#define MTC_CRADJ		22	/* synonym for credit adj	*/
#define MTC_CHQDGU		23	/* cheque deposit guarantee	*/
#define MTC_CHQDEP		24	/* cheque deposit		*/
					/* NMR006996 WLi 13/02/2002 */
#define	MTC_CHFUNDSXFER		26	/* cardholder funds transfer	*/
#define MTC_NIGHTSAFEDEP	27	/* Nightsafe deposit		*/
#define MTC_CASHIN		28	/* cash deposit (counted by ATM)*/
#define MTC_FUNDS_DISBUR	29	/* funds disbursement		*/
#define MTC_MAX_CREDIT		29	/* maximum credit code		*/

					/* 30-39 Inquiries		*/
#define MTC_MIN_ENQUIRY		30	/* minimum enquiry code		*/
#define MTC_INQAVL		30	/* available funds enquiry	*/
#define MTC_INQBAL		31	/* balance enquiry		*/

#define MTC_INTERIMSTMT		34	/* Interim Statement		*/
#define	MTC_TELE2		34	/* Parex special		*/
#define MTC_ASSETVIEW		36	/* Assets overview		*/
#define MTC_PENSIONBAL		37	/* Pension balance enquiry	*/
#define MTC_MINIST		38	/* mini statement PRIVATE	*/
#define MTC_FULLST		39	/* full statement PRIVATE	*/
#define MTC_MAX_ENQUIRY		39	/* maximum enquiry code		*/

					/* 40-49 Transfers		*/
#define MTC_MIN_XFER		40	/* minimum transfer code	*/
#define MTC_CHXFER		40	/* cardholder accounts transfer	*/
#define MTC_MAX_XFER		49	/* maximum transfer code	*/

					/* 50-59 payment services	*/
#define MTC_MIN_PYMNT		50	/* minimum payment code		*/
#define MTC_PYMNT		50	/* Payment			*/
#define MTC_PAYEXTBANK		58	/* Payment to external bank	*/
#define MTC_CCPYMNT		59	/* Credit card bill payment	*/
#define MTC_MAX_PYMNT		59	/* maximum payment code		*/

					/* 60-99 reserved		*/
#define	MTC_CHPIN		90	/* change PIN PRIVATE		*/
#define MTC_LOGONLY		91	/* log only txn PRIVATE		*/
#define MTC_TELECODE_VER        92      /* Telecode verification code   */
#define MTC_CATREQ	        93      /* Customer Authentication Terminal request code   */
#define MTC_PINUNBLK		94	/* PIN Unblock (EMV) 		*/
#define MTC_APPUNBLK		95	/* Application Unblock (EMV)	*/
					/* NMR013700 WLi 23/5/2005	*/
#define	MTC_AVS			96	/* Address Verification only	*/

					/* the following definitions	*/
					/* are INTERNAL ONLY and must	*/
					/* never be passed outside of	*/
					/* Cortex			*/
#define MTC_INT_ACDTLS		100	/* account details request	*/
#define MTC_CHPIN_ORG		101	/* change PIN original		*/
#define MTC_CHPIN_NEW1		102	/* change PIN first new		*/
#define MTC_CHPIN_NEW2		103	/* change PIN second new	*/
#define MTC_CAPTURE_CRD		104	/* capture card, N11085 WLi 16/3/04 */
#define MTC_CUST_DET		105	/* cust details, N21512 IG 07Nov07 */
#define MTC_CASH_DCC_QUERY	106	/* (Cash txn) Ask DCC question  */

					/* for web service, N14859 WLi 11/1/06*/
#define MTC_WSV_CRDACT		200	/* card activation		*/
#define	MTC_WSV_CRDLOAD		201	/* card load			*/
#define	MTC_WSV_STATCHG		202	/* status change		*/
#define	MTC_WSV_BALENQ		203	/* balance enquiry		*/
#define	MTC_WSV_ACCENQ		204	/* account enquiry		*/
#define	MTC_WSV_CRDLST		205	/* card list enquiry		*/
#define	MTC_WSV_LOADVER		206	/* load verification		*/
#define	MTC_WSV_CRDXFER		207	/* card transfer		*/
#define	MTC_WSV_CASHOUT		208	/* cash out			*/
#define	MTC_WSV_CNCLOAD		209	/* cancel load			*/

					/*  Amount type codes		*/
#define	ATC_ACC_LEDGER		1	/* Account ledger balance	*/
#define	ATC_ACC_CREDIT_REMAIN	1	/* Credit a/c: credit remaining	*/
#define	ATC_ACC_CLEARED		ATC_ACC_LEDGER
#define	ATC_ACC_AVAILABLE	2	/* Account available balance	*/
#define	ATC_ACC_CREDIT_LIMIT	2	/* Credit a/c: credit limit	*/
#define	ATC_AMT_OWING		3	/* Amount owing			*/
#define	ATC_AMT_DUE		4	/* Amount due			*/
#define	ATC_ACC_AVLCR		5	/* Account available credit	*/
/* According to ISO8583:2003 */
#define	ATC_ACC_BLOCKED		10	/* Blocked ammount		*/
#define ATC_ACC_ON_HOLD		ATC_ACC_BLOCKED
#define	ATC_ACC_UNCLEARED	16	/* Account unclear balance 	*/
					/* internal usage		*/
#define	ATC_AMTREMCYCL		20	/* Amount remaining this cycle	*/
#define	ATC_ACC_CREDLIM_CTX	21	/* Credit Limit			*/
#define	ATC_AMTCASH		40	/* Amount cash			*/
#define	ATC_AMTGOODS		41	/* Amount goods and services	*/

					/* Alternative balances for WBK */
#define	ATC_AVL_CASH_WBK	50	/* Available Cash		*/
#define	ATC_REAL_BAL_WBK	51	/* Real Balance			*/
#define	ATC_LIMIT_WBK		52	/* Limit			*/

					/* Account types		*/
#define	ACC_TYPE_DFLT		0	/* Default - unspecified account*/
#define	ACC_TYPE_DEFAULT	0	/* Default - unspecified account*/
#define	ACC_TYPE_UNKNOWN	ACC_TYPE_DFLT
#define	ACC_TYPE_SAVINGS	10	/* Savings account		*/
#define	ACC_TYPE_CHEQUE		20	/* Cheque account		*/
#define	ACC_TYPE_CREDIT		30	/* Credit account		*/
#define	ACC_TYPE_CREDIT_CORP	39	/* Corporate Credit account(ep06.2)*/
#define	ACC_TYPE_UNIVERSAL	40	/* Universal account		*/
#define	ACC_TYPE_INVESTMENT	50	/* Investment account		*/
#define ACC_TYPE_STORED_VALUE	60	/* Stored Value account		*/
#define ACC_TYPE_SPECIFIED	100	/* Used within ia 		*/

#define	CRD_ACPT_BUS_TYPE_ATM			6011
#define	CRD_ACPT_BUS_TYPE_MCD			6010
#define	CRD_ACPT_BUS_TYPE_MAS			6012 /* B.Aspland - 21/12/99 */
#define	CRD_ACPT_BUS_TYPE_MAIL_ORDER		5961
#define	CRD_ACPT_BUS_TYPE_MAIL_ORDER2		4816 /* Alternative VISA */
#define	CRD_ACPT_BUS_TYPE_WIRE_TRANSFER		4829
#define	CRD_ACPT_BUS_TYPE_MONEY_ORDERS		6051
#define	CRD_ACPT_BUS_TYPE_OVERPAYMENTS		6611
#define	CRD_ACPT_BUS_TYPE_SAVINGS_BONDS		6760
#define	CRD_ACPT_BUS_TYPE_HOSPITAL_WITHDRAWAL	7280
#define	CRD_ACPT_BUS_TYPE_GOV_LOAN_PAYMENTS	9411
#define	CRD_ACPT_BUS_TYPE_BETTING		7995
#define CRD_ACPT_BUS_TYPE_TELEPHONE		4814


/* M.Davey 27/8/2003 - New/old/neither card indicator
 * Based on genauth checking C_DATEEXP against crddet's expdate + old_expdate
 * C_CARDNEWOLD values: */
#define	MEXPDATE_NEW	2	/* C_DATEEXP = CRDDET.expdate (new) */
#define MEXPDATE_OLD	1	/* C_DATEEXP = CRDDET.old_expdate (old) */
#define MEXPDATE_BAD	0	/* C_DATEEXP present but no match */
#define MEXPDATE_ERROR	(-1)	/* Expiry date missing/error */
#define MEXPDATE_MISSING (-1)	/* Expiry date missing/error */

/************************************************************************/
/**** Standard Card Service codes, ISO based				*/
/*    (Not all values necessarily available for all card types)		*/
/************************************************************************/
					/* Service code digits		*/
					/* digit 1			*/
#define SVCC1_INTL	'1'		/* standard international card	*/
#define SVCC1_INTLCHIP	'2'		/* international card - chip	*/
#define SVCC1_LOCL	'5'		/* standard national-use card	*/
#define SVCC1_LOCLCHIP	'6'		/* national-use card - chip	*/
#define SVCC1_PROP	'7'		/* proprietary label card	*/
#define SVCC1_TEST	'9'		/* (old) Test card (usage unclear)*/
					/* digit 2			*/
#define SVCC2_AUTH	'0'		/* standard authorisation	*/
#define SVCC2_POSITIVE	'2'		/* positive authorisation only	*/
#define SVCC2_POSITIVESP '4'		/* (old) positive auth, unless special
					 * bilateral agreement 		*/
#define SVCC2_NATICC 	'6'		/* (old) National/ICC		*/
#define SVCC2_PROP	'7'		/* (old) Private / Proprietary	*/

					/* digit 3			*/
#define SVCC3_PINREQ	'0'		/* PIN required (from Oct 96)	*/
#define SVCC3_STDVER	'1'		/* standard verification	*/
#define SVCC3_OLDGOODS	'2'		/* goods/services only		*/
#define SVCC3_ATMONLY	'3'		/* ATM only, PIN required 	*/
#define SVCC3_CASHONLY	'4'		/* (old) Cash Only */
#define SVCC3_PINGOODS	'5'		/* PIN required, goods/svcs only */
#define SVCC3_PINIFPAD	'6'		/* Prompt for PIN if PIN pad	*/
#define SVCC3_PADGOODS	'7'		/* PIN if PIN pad, goods/svcs only */

#define SVCCODE_ICVV	"999"		/* used for calc iCVV */

/*************************************************************************/
/*************************************************************************/
/**** THE FOLLOWING ARE ALL NOMAD-SPECIFIC, NOT ISO-RELATED IN ANY WAY ***/
/*************************************************************************/
/*************************************************************************/
#define	CRDGRP_ON_US_LOCAL	'0'
#define	CRDGRP_ON_US_INTER	'1'
#define	CRDGRP_NOT_ON_US_LOCAL	'2'
#define	CRDGRP_NOT_ON_US_INTER	'3'

#define	AUTH_TIME_DAYS		1
#define	AUTH_TIME_HOURS		2
#define	AUTH_TIME_MINUTES	3

#define VISA_SCHEME_BG		"VISA"	/* scheme name for VISA		*/
#define PLUS_SCHEME_BG		"PLUS"	/* scheme name for PLUS		*/
#define HBK_SCHEME_BG		"HBK"	/* scheme name for HBK Local D*H*/
#define SWITCH_SCHEME_BG	"SWITCH"
/*#define EUROPAY_SCHEME_BG	"EUROPAY"	 NOT USED !!!		*/
#define	EUROCARD_SCHEME_BG	"ECRD"
#define MASTERCARD_SCHEME_BG	"MCRD"
#define	EURO_CIRRUS_SCHEME_BG	"CIRR"
#define	EDC_MAESTRO_SCHEME_BG	"MAES"
#define	CIRRUS_MAESTRO_SCHEME_BG	"CIMA"
#define	AMEX_SCHEME_BG		"AMEX"	/* NMR011573 WLi 15/7/2004	*/

					/* Response sources		*/
#define RSPSRC_DRIVER		'D'	/* low level driver, pre-CTH	*/
#define RSPSRC_CORE		'C'	/* core transaction handler	*/
#define RSPSRC_CTXISS		'I'	/* Cortex issuer (debauth)	*/
#define RSPSRC_HOST		'H'	/* Host response		*/
#define RSPSRC_NETWORK		'N'	/* Network response		*/
#define RSPSRC_VISASTIP		'V'	/* VISA standin processing	*/
#define RSPSRC_INTERFACE	'F'	/* Interface between CTH/host	*/
					/* NMR009810 WLi 01/7/2003	*/
#define	RSPSRC_CTXVSW		'X'	/* CORTEX VISA switch		*/
					/* for device rejects, WLi 10/2000 */
#define	RSPSRC_ATM		'A'	/* ATM driver			*/
#define	RSPSRC_POS		'P'	/* POS client			*/

					/* Response reasons		*/
#define RSPREAS_VISA_EXPFILE	'0'	/* Auto exception file change	*/
#define RSPREAS_VISA_STIPATR	'1'	/* STIP response / ATR		*/
#define RSPREAS_VISA_STIPLIM	'2'	/* STIP response / below floor	*/
#define RSPREAS_VISA_STIPISI	'3'	/* STIP response / issuer SI	*/
#define RSPREAS_VISA_STIPINA	'4'	/* STIP response / issuer N/A	*/
#define RSPREAS_VISA_ISSUER	'5'	/* Issuer response		*/
#define RSPREAS_VISA_3PARTY	'6'	/* Issuer requested STIP rsp	*/
#define RSPREAS_VISA_POSSDUP	'7'	/* Possible duplicate txn	*/
#define RSPREAS_VISA_DUPADV	'8'	/* Duplicate authorisation	*/
#define RSPREAS_VISA_ARS	'9'	/* Response from ARS		*/
#define RSPREAS_VISA_TELVIDS	'T'	/* Telecode file change (VIDS)	*/
#define RSPREAS_VISA_TELLIM	'U'	/* Telefile chg (bad tries)	*/
#define RSPREAS_VISA_TELUSG	'V'	/* Telefile chg (usage)		*/

					/* Reject reasons		*/
					/* codes 1-499 Core Txn Handler	*/
#define RJR_CTH_UNSNTISS	1	/* Unable to send to issuer	*/
#define RJR_CTH_NOPAN		2	/* No PAN in message		*/
#define RJR_CTH_NOCRDROUT	3	/* Unable to set card routing	*/
#define RJR_CTH_FBUPDATE	4	/* Unable to update FBFR	*/
#define RJR_CTH_NOAIID		5	/* No AIID in message		*/
#define RJR_CTH_NOAIIDROUT	6	/* Unable to set AIID routing	*/
#define RJR_CTH_NOORIG		7	/* Unable to find orig txn	*/
#define RJR_CTH_ORGDIFF		8	/* Orig txn different from rev	*/
#define RJR_CTH_NEWTXN		9	/* Failed to create transaction	*/
#define RJR_CTH_GETTXN		10	/* Failed to get transaction	*/
#define RJR_CTH_ADDLOG		11	/* Failed to add txn to tlog	*/
#define RJR_CTH_NOTCODE		12	/* No tcode in message		*/
#define RJR_CTH_NEWORG		13	/* Failed to create org txn	*/
#define RJR_CTH_GETORG		14	/* Failed to get org txn	*/
#define RJR_CTH_GETSTATE	15	/* Failed to get txn state	*/
#define RJR_CTH_CHKRPT		16	/* Failed to check repeat	*/
#define RJR_CTH_CHKRSP		17	/* Failed to check response	*/
#define RJR_CTH_ASKSTAN		18	/* Failed to ask for STAN	*/
#define RJR_CTH_GETMSGT		19	/* Failed to get msg type	*/
#define RJR_CTH_UPDLOG		20	/* Failed to update TLOG	*/
#define RJR_CTH_STRTTIM		21	/* Failed to start timer	*/
#define RJR_CTH_STOPTIM		22	/* Failed to stop timer		*/
#define RJR_CTH_NORPLYADD	23	/* No reply address in message	*/
#define RJR_CTH_INETNEW		24	/* Failed to create INET nap	*/
#define RJR_CTH_INETCON		25	/* Failed to connect INET	*/
#define RJR_CTH_INETSND		26	/* Failed to send INET		*/
#define RJR_CTH_INETPOL		27	/* Failed to poll INET		*/
#define RJR_CTH_INETRDIS	28	/* Failed to rcv discon INET	*/
#define RJR_CTH_SETSTATE	29	/* Failed to set txn state	*/
#define RJR_CTH_GENREV		30	/* Failed to change txn to rev	*/
#define RJR_CTH_STRTREV		31	/* Failed to start rev		*/
#define RJR_CTH_BADTSTATE	32	/* Invalid tstate		*/
#define RJR_CTH_BADMSGT		33	/* Invalid msgtype		*/
#define RJR_CTH_BEGIN		34	/* Unable to BEGIN sql		*/
#define RJR_CTH_COMMIT		35	/* Unable to COMMIT sql		*/
#define RJR_CTH_ROLLBK		36	/* Unable to rollback txn	*/
#define RJR_CTH_SNDTRM		37	/* Unable to send to terminal	*/
#define RJR_CTH_SNDISS		38	/* Unable to send to issuer	*/
#define RJR_CTH_SNDAUTH		39	/* Unable to send to authoriser	*/
#define RJR_CTH_SETORG		40	/* Failed to set org txn data	*/
#define RJR_CTH_UPDRPT		41	/* Failed to update to repeat	*/
#define RJR_CTH_GETTIM		42	/* Get timer data		*/
#define RJR_CTH_UPDRSP		43	/* Unable to update response	*/
#define RJR_CTH_FBALLC		44	/* Unable to allocate FB	*/
#define RJR_CTH_GETRPLY		45	/* Unable to get reply		*/
#define RJR_CTH_CALLRTE		46	/* Unable to call routing svc	*/
#define RJR_CTH_READRTE		47	/* Unable to read routing rec	*/
#define RJR_CTH_NOCLS		48	/* No message class in msg	*/
#define RJR_CTH_GETSVGRP	49	/* Unable to get server group	*/
#define RJR_CTH_GETSVCNM	50	/* Unable to get service name	*/
#define RJR_CTH_BADURC		51	/* Bad user return code		*/
#define RJR_CTH_NOASRVG		52	/* ASRVGRP not im message	*/
#define RJR_CTH_FINRSPTIM	53	/* Failed to start fin rsp	*/
#define RJR_CTH_SETRSPD		54	/* Failed to set response pend.	*/
#define RJR_CTH_TIMEOUT		55	/* Transaction response timeout	*/
#define RJR_CTH_ADDQUEUE	56	/* Unable to add to /Q		*/
#define RJR_CTH_DEQUEUE		57	/* Unable to delete from /Q	*/
#define RJR_CTH_SETVOID		58	/* Unable to set TS VOID	*/
#define RJR_CTH_SETCMPLT	59	/* Unable to set TS Cmplt OK	*/
#define RJR_CTH_PREVTXNDIFF	60	/* Repeated txn but diff PAN & amt */
#define RJR_CTH_NOT2		61	/* Failed to read T2 from fb 	*/
#define RJR_CTH_REV2		62	/* Reversal already rcd for txn	*/
#define RJR_CTH_NEGAMT		63	/* -ve or 0 amt			*/
#define RJR_CTH_PANTOOLONG	64	/* PAN too long			*/

#define RJR_ACCLIM_EXCEED	121	/* ACCLIM num/value exceeded 	*/
#define RJR_CRDLIM_EXCEED	122	/* CRDLIM num/value exceeded 	*/

					/* codes 500-599 VISA Net I/f	*/
#define RJR_VIF_VISAREJ		500	/* VISA rejected		*/
#define RJR_VIF_MSGCVOUT	501	/* Message conversion FB->ISO	*/
#define RJR_VIF_MSGCVIN		502	/* Message conversion ISO->FB	*/
#define RJR_VIF_NONATMSG	503	/* Failed to get NATMSG from FB	*/
#define RJR_VIF_SENDDRV		504	/* Failed to send to driver	*/
#define RJR_VIF_RSPTOUT		505	/* Response timed out		*/
#define RJR_VIF_RSP102		506	/* Response to the 102		*/
#define RJR_VIF_INVTRN		507	/* Invalid Transaction		*/

					/* codes 600-799 debauth/crauth	*/
#define RJR_CIS_CRDSTAT		600	/* card status bad		*/
#define RJR_CIS_EXPDATE		601	/* card expired			*/
#define RJR_CIS_CVVFAIL		602	/* CVV validation failed	*/
#define RJR_CIS_ATMONLY		603	/* ATM only card in non-ATM txn	*/
#define RJR_CIS_GOODSONLY	604	/* Goods/ATM card,non-ATM cash	*/
#define RJR_CIS_CRDSVCS		605	/* Txn not in allowed card svcs	*/
#define RJR_CIS_NOEXPTRK	606	/* No expiry date with trk data	*/
#define RJR_CIS_NOEXPNOTRK	607	/* No expiry date, no trk data	*/
#define RJR_CIS_EXPNEDBTRK	608	/* Expiry<>DB, trk data in msg	*/
#define RJR_CIS_EXPNEDBNTRK	609	/* Expiry<>DB, no trk data	*/
#define RJR_CIS_CRDEXP		610	/* Expiry < today		*/
#define RJR_CIS_PINREQSVC	611	/* PIN required (svc code card)	*/
#define RJR_CIS_PINREQATM	612	/* PIN required (ATM txn)	*/
#define RJR_CIS_FBERROR		613	/* Unable to get/update FBFR	*/
#define RJR_CIS_NOPINBLK	614	/* No PIN block record for card	*/
#define RJR_CIS_PVVFAIL		615	/* PVV validation failed	*/
#define RJR_CIS_PINBLKFAIL	616	/* PIN block validation failed	*/
#define RJR_CIS_BADPIN		617	/* Incorrect PIN entered	*/
#define RJR_CIS_UPDPINTRY	618	/* Update PIN try failed	*/
#define RJR_CIS_MAXPINTRY	619	/* Maximum PIN tries reached	*/
#define RJR_CIS_LOCALONLY	620	/* Card local use only		*/
#define RJR_CIS_CRDROUTFB	621	/* Can't get FB CRDROUTING	*/
#define RJR_CIS_CRDROUTING	622	/* Can't read card routing rec	*/
#define RJR_CIS_CRDFORMAT	623	/* Can't read card format rec	*/
#define RJR_CIS_CRDDET		624	/* Can't read card detail rec	*/
#define RJR_CIS_CRDSTATUS	625	/* Can't read card status rec	*/
#define RJR_CIS_PANSEQFB	626	/* Can't get PAN or SEQ from FB	*/
#define RJR_CIS_NOAPRVL		627	/* No approval code		*/
#define RJR_CIS_APRVLADD	628	/* Add APRVLCODE failed		*/
#define RJR_CIS_UPDCYCLE	629	/* Update card cycle failed	*/
#define RJR_CIS_CRDPIN		630	/* Can't read card PIN record	*/
#define RJR_CIS_UPDCRDPIN	631	/* Update card PIN failed	*/
#define RJR_CIS_NOPANTRK	632	/* No PAN or track data		*/
#define RJR_CIS_PANPOSN		633	/* No PAN position in track fmt	*/
#define RJR_CIS_PANTRKDATA	634	/* No PAN found in track data	*/
#define RJR_CIS_SEQPOSN		635	/* No seq position in track fmt	*/
#define RJR_CIS_SEQTRKDATA	636	/* No seq found in track data	*/
#define RJR_CIS_NOPAN		637	/* No PAN found in FB		*/
#define RJR_CIS_ADDCRDVEL	638	/* Can't add CRDVEL record	*/
#define RJR_CIS_CRDVEL		639	/* Can't read CRDVEL record	*/
#define RJR_CIS_PURVEL		640	/* Purchase velocity check fail */
#define RJR_CIS_CASHVEL		641	/* Cash velocity check failed	*/
#define RJR_CIS_UPDCRDVEL	642	/* Update card velocity failed	*/
#define RJR_CIS_ACCSVCS		643	/* Txn not allowed in acc svcs	*/
#define RJR_CIS_NOSTANDIN	644	/* Host offline, standin n/a	*/
#define RJR_CIS_HOSTSTATE	645	/* Host state 'illegal'		*/
#define RJR_CIS_NOACCTY		646	/* No account of required type	*/
#define RJR_CIS_INVTXNTY	647	/* Invalid transaction type	*/
#define RJR_CIS_LOCMINHOST	648	/* Local ministmt req with host	*/
#define RJR_CIS_BADAPRVL	649	/* Bad (unmatch?) approval code	*/
#define RJR_CIS_CALCCYCLE	650	/* Cycle calculation failed	*/
#define RJR_CIS_CNVCRDCUR	651	/* Card currency conversion fail*/
#define RJR_CIS_CRDAMTREM	652	/* Txn exceeds card amount rem	*/
#define RJR_CIS_CRDOFFREM	653	/* Txn exceeds card offfline rem*/
#define RJR_CIS_BADCURBILL	654	/* Billing curr <> account curr	*/
#define RJR_CIS_ACCAVLBAL	655	/* Txn exceeds account available*/
#define RJR_CIS_FBALLC		656	/* Unable to allocate FB	*/
#define RJR_CIS_HOSTSTAT	657	/* Host status service call fail*/
#define RJR_CIS_HOSTSTRSP	658	/* Host status response error	*/
#define RJR_CIS_BADCNVRT	659	/* Currency convert failed	*/
#define RJR_CIS_LIMITCC		660	/* Usage limit exceeded in chk crd */
#define RJR_CIS_NOTALLOWED	661	/* Service restriction		*/
#define RJR_CIS_LIMITGA		662	/* Usage limit exceeded in get acc */
#define RJR_CIS_GENINFO_FAIL	663	/* Couldnt read geninfo record 	*/
#define RJR_CIS_NO_AUTHREC	664	/* No authorisation to rev	*/
#define RJR_CIS_BAD_TXNCODE	665	/* Bad transaction code		*/
#define RJR_CIS_HOSTDET		666	/* Get host details failed	*/
#define RJR_CIS_NOBALS		667	/* No balances available	*/
#define RJR_CIS_TLIMITS		668	/* Error reading TLIMITS	*/
#define RJR_CIS_NOAMTTXN	669	/* Missing AMTTXN		*/
#define RJR_CIS_NOCURBILL	670	/* Missing CURBILL		*/
#define RJR_CIS_NOAMTBILL	671	/* Missing AMTBILL/CNVRATEBILL	*/
#define RJR_CIS_SUSPFAIL	672	/* Suspend transaction failed	*/
#define RJR_CIS_BADMSGTYP	673	/* Bad message type		*/
#define RJR_CIS_SETOUTBTCH	674	/* Set out batch type		*/
#define RJR_CIS_SETBILL		675	/* Set billing details		*/
#define RJR_CIS_BADAUTHSRC	676	/* Bad authorisation source	*/
#define RJR_CIS_POSTNONSTD	677	/* Post non_std (chgbk etc) txn	*/
#define RJR_CIS_OVRTLIMITS	678	/* TLIMITS exceeded		*/
#define RJR_CIS_NOTXNCODE	679	/* TXNCODE missing		*/
#define RJR_CIS_NOCURTXN	681	/* Missing CURTXN		*/
#define RJR_CIS_BADNETADR	682	/* Missing netadr in genauth	*/
#define RJR_CIS_BADAUTHDET	683	/* Cant read authdet record	*/
#define RJR_CIS_BADRSPSRVCNM	684	/* Cant set up the rsp service  */
#define RJR_CIS_NOACCREC	685	/* No account record		*/
#define RJR_CIS_NOACCTYPREC	686	/* No acc type record		*/
#define RJR_CIS_NOACCSTATREC	687	/* No acc status record		*/
#define RJR_CIS_NOBILLACC	688	/* No bill payment account	*/
#define RJR_CIS_NOBILLTYP	689	/* No bill payment acc type	*/
#define RJR_CIS_NOBILLSTAT	690	/* No bill payment acc status	*/
#define RJR_CIS_XFERSAMETYP	691	/* Xfer, src & dest same type	*/
#define RJR_CIS_ACCSTATUS	692	/* Account status code bad	*/
#define RJR_CIS_CRDPRODREC	693	/* Cant read crdproduct record	*/
#define RJR_CIS_PRODSVCS	694	/* Service not allowd to product*/
#define RJR_CIS_NOSTMT		694	/* No statements available	*/
#define RJR_CIS_EFFDATE		695	/* card not yet effective	*/
#define RJR_CIS_AUTHMODE	696	/* Txn not allowed in mode	*/
#define RJR_CIS_MISSEXP		697	/* Missing expiry date		*/
#define RJR_CIS_CVCFAIL		698	/* CVC validation failed	*/
#define RJR_CIS_INVMCH		699	/* Invalid merchant		*/
#define RJR_CIS_INVEXPDATE	700	/* Invalid expiry date		*/
#define RJR_CIS_NUMVEL		701	/* freq velocity check fail 	*/
#define RJR_CIS_AMTVEL		702	/* amt velocity check fail 	*/
#define RJR_CIS_MISSCVV		703	/* Missing CVV / mandatory	*/
#define RJR_CIS_PINPREFAIL	704	/* PIN pre-validation problem	*/
#define RJR_CIS_EXPMISMATCH	705	/* T2 expiry date <> F14	*/
#define RJR_CIS_INVTRANPROD	706	/* Invalid txncode for product	*/
#define RJR_CIS_NOT1ORT2	707	/* CDIM says track read but not	*/
#define RJR_CIS_EXPMISMATCHSB   708     /* T2 expiry date <> F14 (sig base)       */
#define RJR_CIS_INVT2   	709     /* Corrupted T2			*/
#define RJR_CIS_INVCDIM   	710     /* invalid card data input metho*/
#define RJR_CIS_REQIP   	711     /* request in progress		*/
#define RJR_CIS_CDIMMAG		712	/* Expected MAG or MAGCVV (ELEC)*/
#define RJR_CIS_EC		713	/* Electronic Commerce not supported */
#define RJR_CIS_CVVGENFAIL	714	/* CVV generation failed	*/
#define RJR_CIS_SVCPOSN		715	/* No svc position in track fmt	*/
#define RJR_CIS_SVCTRKDATA	716	/* No svc found in track data	*/
#define RJR_CIS_TELECODEBAD	717	/* Telecode verification failed */
#define RJR_CIS_EPNETREJ	718	/* Europay CVV network reject	*/
#define RJR_CIS_EPINVLDDATA	719	/* Europay CVV inconsistent data*/
#define RJR_CIS_ACQSUSTRAN	720	/* Acquirer suspects transaction*/
#define RJR_CIS_CUSTNOCARD	721	/* Cust present, card not	*/
#define RJR_CIS_PANMISMATCH	722	/* T2 PAN <> F02		*/
#define RJR_CIS_EXPMISMATCH1	723	/* T2 expiry date <> F14, both exp */
/* DMG 5/7/2002 rearranged parex changes into base */
#define RJR_CIS_NOUPD_CRDDET	724	/* Cant update card detail rec  */
#define RJR_CIS_NOEC_PROD	725	/* Can't do Internet with prod  */
#define RJR_CIS_NO_SET		726	/* SET not supported            */
#define RJR_CIS_UNSEC_REJ	727	/* Bank requires security       */
#define RJR_CIS_OVRMAXTXN       728     /* Over refer to issuer limit   */
/* <PRX22010_R1_140> */
#define RJR_CIS_RISKPROC        729     /* Rejected by risk processing  */
#define RJR_CIS_RISKPROCUPD     730     /* CRDLIMITTD update failed     */
#define RJR_CIS_NOMSGFN         731     /* No C_MSGFN in FB */
#define RJR_CIS_NOINSTCODE      732     /* No I_INSTCODE in FB */
/* cashback, NMR007586 WLi 27/05/02 */
#define RJR_CIS_NOAMTTXNCB      733     /* Missing AMTTXNCB             */
#define RJR_CIS_NOAMTBILLCB     734     /* Missing AMTBILLCB            */
/* fallback, NMR008161 WLi 03/09/2002 */
#define	RJR_CIS_FALLBACKLMT	735	/* fallback limit exceeded	*/
/* authorization conditions check, NMr008428 WLi 25/10/2002 */
#define	RJR_CIS_AUTHCHKREJ	736	/* auth conditions check reject	*/
#define RJR_CIS_UPDCCACC	737	/* Call to UPDCCACC failed	*/
/* CAVV validation, NMR010959 WLi 26/2/2004 */
#define RJR_CIS_CAVVGENFAIL	738	/* CAVV generation failed	*/
#define RJR_CIS_CAVVFAIL	739	/* CAVV validation failed	*/
#define RJR_CIS_MISSCAVV	740	/* Missing CAVV or CAVV data	*/
#define RJR_CIS_CAVVINVDATA	741	/* CAVV data is invalid		*/
#define RJR_CIS_CAVVAUTHBAD	742	/* CAVV authentication not suc	*/
#define	RJR_CIS_LOCKACCDET	743	/* Failed to lock ACCDET	*/
#define RJR_CIS_PINCONVFAIL	744	/* PIN block enc translate fail */
#define RJR_CIS_PVVGENFAIL	745	/* PVV Generation failed	*/
/* CSCs validation, NMR011577 WLi 15/7/2004 */
#define RJR_CIS_CSCGENFAIL	746	/* CSCs generation failed	*/
#define RJR_CIS_4CSCFAIL	747	/* 4CSC validation failed	*/
#define RJR_CIS_5CSCFAIL	748	/* 5CSC validation failed	*/
/* CN N15775 April 06 EBP 1.5 additional codes */
#define RJR_ACCSTAT_DENYSVC	750	/* Txncode in accstatus deny svc*/
#define RJR_CRDACCROLE_DENYSVC	751	/* Txn denied svc in CrdAcc role*/
#define RJR_CIS_OLD_CARD	752	/* Txn not allowed on old card  */
#define RJR_CIS_CRDMRCHB	753	/* Txn blocked by CRDMRCHB table*/
#define	RJR_CIS_CRDACT_AUTHCHKREJ 754	/* auth conditions check rejected*/
					/* card activation */
#define RJR_CIS_INVT1   	755     /* Corruptedi/Invalid T1	*/
#define RJR_CIS_CRDPFEAT	756	/* not allowed CRDPRODUCT.features */
#define RJR_CIS_BAD_ATC		757	/* ATC backwards or duplicate	*/
					/* (see also EMV RJRs 87x which 
					 *  genauth can generate)	*/
#define RJR_CIS_WRONGSVCCODE	758	/* Svccode in msg<>crddet	*/

					/* codes 800-899 interface	*/
#define RJR_IF_REJECT		800	/* I/f rejected			*/
#define RJR_IF_MSGCVOUT		801	/* Message conversion FB->ISO	*/
#define RJR_IF_MSGCVIN		802	/* Message conversion ISO->FB	*/
#define RJR_IF_NONATMSG		803	/* Failed to get NATMSG from FB	*/
#define RJR_IF_SENDDRV		804	/* Failed to send to driver	*/
#define RJR_IF_RSPTOUT		805	/* Response timed out		*/
#define RJR_IF_HOSTDET		806	/* Failed to get host detail	*/
#define RJR_IF_OFFLINE		807	/* offline			*/
#define RJR_IF_SIGNEDOFF	808	/* interface signed off		*/

					/* for Bankmaster Interface	*/
#define RJR_IF_COMM_PROB	809	/* Communication problem */
#define RJR_IF_DEST_NOTONNET	810	/* Dest branch on network */
#define RJR_IF_FAILED_TRANS	811	/* Failed transaction */
#define RJR_IF_REFER_TO_SUPV	812	/* eg insuff funds, refer to supv */
#define RJR_IF_FRCPST_REC_LOCK	813	/* force post trans failed */
#define RJR_IF_SEVERE_ERR	814	/* severe error */
#define RJR_IF_FATAL_ERR	815	/* fatal error */
#define RJR_IF_CUSTRECNOTFOUND	816	/* could not find customer record */
#define RJR_IF_CARD_SINGLE_ERR	817	/* one error */
#define RJR_IF_CARD_MANY_ERRS	818	/* multiple errors */
#define RJR_IF_CONACC		819	/* Error with contra-account server */

					/* more generic interface errors*/
#define RJR_IF_FAILED		820	/* I/f collapsed		*/
#define RJR_FRD_NOCHECK		821	/* fraud check(s) not performed */

					/* ATM/POS rejects, WLi 20/10/00 */
#define	RJR_POS_FRAUD		830	/* txn fraud in pos client	*/
#define	RJR_POS_CHKFRDF		831	/* check fraud failed in pos client */
#define	RJR_POS_TXNREQF		832	/* txn req failed in pos client	*/
#define	RJR_POS_MAKREVF		833	/* make rev failed in pos client */
#define	RJR_POS_TXNREQTOUT	834	/* org txn tpcall(TXNREQ) timeout*/
#define	RJR_ATM_GETTXNF		840	/* get txn failed in atm driver */
#define	RJR_ATM_ACINFO1		841	/* get account 1 info failed in atm */
#define	RJR_ATM_ACINFO2		842	/* get account 2 info failed in atm */
#define RJR_ATM_EMV_AAC		843	/* EMV ICC returned AAC in atm	*/
/* Auto cash deposit ATM rejects */
#define RJR_ATM_COUNTERFEIT	844	/* ATM got Level 2 counterfeit notes */
#define RJR_ATM_MULTICURR	845	/* ATM Multicurrency deposit tried */
#define RJR_ATM_RETRACT_FIXED	846	/* ATM retracted fixed amount */
#define RJR_ATM_RETRACT_UNKN	847	/* ATM retracted unknown amount */
#define RJR_ATM_MACERR		848	/* MAC error, NMR010766 WLi 28/1/2004 */
					/* See also RJR_EMV_... rejects */

					/* get db info failed in pos client */
					/* WLi 19/03/2001		*/
#define	RJR_POS_DBINFO		850	/* general error		*/
#define	RJR_POS_DB_TERMCODE	851	/* termcode error		*/
#define	RJR_POS_DB_MRCH_ST	852	/* merchant status error	*/
#define	RJR_POS_DB_MRCH_SC	853	/* merchant scheme error	*/
#define	RJR_POS_DB_MRCH_NO	854	/* merchant no error		*/
#define	RJR_POS_DB_MRCH_GT	855	/* get merchant failed		*/
#define	RJR_POS_DB_MRCH_LC	856	/* set merchant loc failed	*/
#define	RJR_POS_DB_MRCH_CC	857	/* invalid  merchant cat code	*/
#define	RJR_POS_DB_CRD_SC	858	/* card scheme error		*/
#define	RJR_POS_DB_CRD_RT	859	/* card routing error		*/
#define	RJR_POS_DB_BRANCH	860	/* get branch failed		*/
#define	RJR_POS_DB_CURRCODE	861	/* no currency			*/
#define	RJR_POS_DB_CTRYCODE	862	/* no country			*/
#define	RJR_POS_DB_INSTCODE	863	/* no instcode			*/
					/* Middleware interface errors	*/
#define	RJR_NO_SERVICE		864	/* MW service not available 	*/
#define RJR_MISSING_FIELD	865	/* Missing field in FB		*/
#define RJR_MW_MSGCVOUT		866	/* Error converting outgoing msg*/
#define RJR_NO_CHDEBACC		867	/* Cant get deb acc for ch card */
#define RJR_MW_MSGCVIN		868	/* Error converting outgoing msg*/
#define RJR_MW_REJECT		869	/* Middleware returned error	*/
#define RJR_MW_MISMATCH		870	/* Resp does not match req	*/

					/* NMR008049 WLi 28/08/2002	*/
					/* EMV authorization rejects	*/
#define RJR_EMV_CRPTFAIL	871	/* cryptogram verification fail	*/
#define	RJR_EMV_ATCUPDFL	872	/* ATC update fail		*/
#define	RJR_EMV_OTHERERR	873	/* other EMV error		*/
#define RJR_EMV_NO_1GEN_AC	874	/* 1st Gen AC failed - no AC	*/
#define RJR_EMV_NO_2GEN_AC	875	/* 2nd Gen AC failed - no AC	*/

					/* Mobile Topup (BZWBK)		*/
#define RJR_TUIF_HOFFLN		900	/* Host Off Line		*/
#define RJR_TUIF_MSGCVOUT  	901	/* FB - > Nat Conversion failed	*/
#define RJR_TUIF_HOSTDET	902	/* Unable to get Host details	*/
#define RJR_TUIF_NONATMSG 	903 	/* Not a native message		*/
#define RJR_TUIF_SENDDRV  	904	/* Could not send to vidrv	*/
#define RJR_TUIF_HTOUT 		905	/* Host Time Out		*/
#define RJR_TUIF_UNKNOWN 	906	/* Unknown Error		*/
#define RJR_TUIF_MSGCVIN  	907	/* Nat -> FB Conversion failed	*/
#define RJR_TUIF_AMTSMALL 	908	/* Amttxn < min on interface	*/
#define RJR_TUIF_AMTBIG 	909	/* Amttxn > max on interface	*/
#define RJR_TU_CALLRTE		1001 	/* Call to topuprte fail 	*/
#define RJR_TU_GETMSGT 		1002	/* Failed to get msg type 	*/
#define RJR_TU_NOTOPUPNO	1003	/* No topup number in msg	*/
#define RJR_TU_CALLCTH 		1004	/* Call to ctxnh fail		*/
#define RJR_TU_ENQCTH 		1005	/* tpenqueue to ctxnh failed 	*/
#define RJR_TU_NOQUEUE 		1006	/* no queue name in msg		*/
#define RJR_TU_TULOG		1007	/* Call to topuplog fail	*/
#define RJR_TU_NOTURSP 		1008	/* No topup response in msg	*/
#define RJR_TU_NOTVER 		1009	/* topup number	not verified	*/
#define RJR_TU_ERRVER 		1010	/* error in topup verification	*/
#define RJR_TU_NORSPCODE 	1011	/* No C_RSPCODE in msg		*/
#define RJR_TU_NOACTIONCODE 	1012	/* No C_ACTIONCODE in msg	*/
#define RJR_TU_FINDCLND 	1013	/* Financial txn declined 	*/
#define	RJR_TU_FBUPDATE		1014 	/* fielded buffer update fail	*/
#define	RJR_TU_FBDEL		1015 	/* fielded buffer delete fail	*/
#define	RJR_TU_TUREJ		1016 	/* topup rejected by host	*/
#define	RJR_TU_TUFAIL		1017 	/* error in topup		*/
#define	RJR_TU_TUREVFAIL	1018 	/* error in topup reversal 	*/
#define RJR_TU_NOTOPUPSVC	1019 	/* Failed to get I_TUSVC 	*/
#define RJR_FDS_REJECT		1020	/* FDS specific - normal reject */
#define RJR_FDS_REJECT_PU	1021	/* FDS specific - rej/pickup	*/
/* CN 11/10/04 NMR011957 reject reason for new allow check server	*/
#define RJR_ALLOWCHECK		1030	/* Rjct'd by ALLOWCHECK server	*/

					/* NMR010959 WLi 26/2/2004	*/
					/* CAVV authentication results code */
#define	CAVVAUTHRS_SUCCEED	'0'	/* Succeessful			*/
#define	CAVVAUTHRS_NOTPERF	'5'	/* Could not be performed	*/
#define	CAVVAUTHRS_FAIL		'9'	/* Failed			*/
#define	CAVVAUTHRS_ATTEMPT	'7'	/* Attempt			*/
#define	CAVVAUTHRS_ACSNAV	'8'	/* Attempt, issuer ACS not avaiable*/
					/* CAVV results code		*/
#define	CAVV_AUTHRS_INVALID	'0'	/* CAVV auth results invalid	*/
#define	CAVV_AUTH_FAIL		'1'	/* CAVV failed validation - auth */
#define	CAVV_AUTH_SUCCEED	'2'	/* CAVV passed validation - auth */
#define	CAVV_ATTM_SUCCEED	'3'	/* CAVV passed validation - attempt */
#define	CAVV_ATTM_FAIL		'4'	/* CAVV failed validation - attempt */
#define	CAVV_ISS_NOTPAR		'6'	/* issuer not participate, VISA use */
#define	CAVV_ATTM_FAIL_US7	'7'	/* as 4 for US card		*/
#define	CAVV_ATTM_SUCCEED_US7	'8'	/* as 3 for US card		*/
#define	CAVV_ATTM_FAIL_US8	'9'	/* as 4 for US card		*/
#define	CAVV_ATTM_SUCCEED_US8	'A'	/* as 3 for US card		*/
#define	CAVV_INFO_SUCCEED	'B'	/* CAVV passed validation - info */
#define	CAVV_ATTM_INVALID	'C'	/* CAVV not validate-attempt, VISA use*/
#define	CAVV_AUTH_INVALID	'D'	/* CAVV not validate-attempt, VISA use*/


					/* Mastercard STIP SecureCode
					 * AAV results (ie Mcrd CAVV STIP) */
#define MC_AAV_VALID		'V'	/* AAV checked and valid	*/
#define MC_AAV_INVALID		'I'	/* AAV checked and invalid	*/
#define MC_AAV_UNCHECKED	'U'	/* AAV has not been checked	*/

					/* Mastercard STIP Application
					 * Cryptogram (AC) (DE048.PDS71)
					 * validation results code 	*/
#define MC_AC_ARQCOK		'V'	/* AC=ARQC and TVR/CVR all valid*/
#define MC_AC_UNCHECKED		'U'	/* AC not checked		*/
#define MC_AC_INVALID		'I'	/* AC not valid			*/
#define MC_AC_OK_NOT_ARQC	'G'	/* AC valid, but not ARQC	*/
#define MC_AC_OK_BADTVRCVR	'T'	/* AC valid, but TVR/CVR invalid*/

/* VM - NMR012302 - Generic host network management changes
 * Generic network management codes used to request interface to
 * send messages to host, interface services should in turn build
 * the full message and send it to host
 */
#define NMGTYPE_ECHO		0	/* send echo	*/
#define NMGTYPE_SIGNON		1	/* send signon	*/
#define NMGTYPE_SIGNOFF		2	/* send signoff	*/

					/* terminal types, N20055 WLi 15/8/06 */
#define	CTXTERMTYPE_UNSP	'0'	/* unspecified			*/
#define	CTXTERMTYPE_LAT		'1'	/* limited amount terminal	*/
#define	CTXTERMTYPE_ATM		'2'	/* ATM				*/
#define	CTXTERMTYPE_SSTADM	'3'	/* self-service or ADM		*/
#define	CTXTERMTYPE_ECR		'4'	/* electronic cash register	*/
#define	CTXTERMTYPE_HMT		'5'	/* home terminal		*/
#define	CTXTERMTYPE_TEL		'7'	/* telephone			*/
#define	CTXTERMTYPE_ADM		'A'	/* automated dispensing machine	*/
#define	CTXTERMTYPE_SST		'B'	/* self-service terminal	*/
#define	CTXTERMTYPE_IFCT	'D'	/* in-flight commerce terminal	*/
#define	CTXTERMTYPE_TRNSPND	'G'	/* transponder			*/
#define	CTXTERMTYPE_MAN		'M'	/* manual, no terminal		*/
/*---------------------------Enums--------------------------------------*/
/*---------------------------Enums--------------------------------------*/
/*---------------------------Typedefs-----------------------------------*/
/*---------------------------Globals------------------------------------*/
/*---------------------------Statics------------------------------------*/
/*---------------------------Prototypes---------------------------------*/
#endif

